### ISSUE TITLE
Problem with SSLIOP_Factory 

### ISSUE THREAD

**Issue by KamilSoko** [DOCGroup/ACE_TAO#1031]
Hello, 

I am new user of ACE/TAO and i am trying to enable SSL on my server. Below is debug log output. I can`t understand why it cannot load SSLIOP_Factory.
My server.conf file looks like it:

dynamic SSLIOP_Factory Service_Object * 
  TAO_SSLIOP:_make_TAO_SSLIOP_Protocol_Factory() 
    "-SSLAuthenticate SERVER_AND_CLIENT -SSLPrivateKey 'PEM:ssl/server-key.pem' -SSLCertificate 'PEM:ssl/server-cert.pem' -SSLCAFile 'PEM:ssl/ca.pem'"

static Client_Strategy_Factory  "-ORBConnectStrategy blocked"

Log output:
2020-01-22 14:52:14.070@<local_host>@3760@LM_DEBUG@TRemoteServerAPI|ACE (3760|8) DSB::instance, repo=00797310, name=SSLIOP_Factory type=00000000 => 00000000
2020-01-22 14:52:14.070@<local_host>@3760@LM_ERROR@TRemoteServerAPI|TAO (3760|8) Unable to load protocol <SSLIOP_Factory>, No such file or directory

I am using OpenSSL 1.1.1

**Comment by jwillemsen** [comment]
Have you compiled ACE/TAO with ssl enabled (ssl is an optional extension, see https://htmlpreview.github.io/?https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/ACE-INSTALL.html#sslinstall)? 

Have you tried compile and run the SSLIOP unit tests, see https://github.com/DOCGroup/ACE_TAO/tree/master/TAO/orbsvcs/tests/Security for all tests that are part of the distribution.

**Comment by KamilSoko** [comment]
Thank you for answer.

I have compiled ACE/TAO with both `ssl = 1` and ` openssl11 =1`.
I have tried to compile tests, however when I run:  `c:\ACE+TAO-6.5.7\ACE_wrappers\bin\mwc.pl" tests.mwc -type vs2017` I get error:  
```
Interpreter.mpc: line 2:
ERROR: Unable to locate parent: portableserver
tests.mwc: line 4:
ERROR: Unable to process unit/Trading/Interpreter/Interpreter.mpc
ERROR: Unable to process: tests.mwc
```
When I tried to compiled it with VS studio. compilation was successful, however when i tried to use `run_test.pl` the output was:
 `fileparse(): need a valid pathname at C:/Strawberry/perl/site/lib/PerlACE/TestTarget.pm line 121`

**Comment by jwillemsen** [comment]
Can you use ACETAO657 as path?

**Comment by KamilSoko** [comment]
I have changed path to c:\ACETAO657\ - the output is the same

**Comment by jwillemsen** [comment]
Have you set ACE_ROOT/TAO_ROOT as environment variables within your command shell?

**Comment by KamilSoko** [comment]
Thank you for yours assistance. 
Env vars was the problem, however after successful (partially - `========== Build: 349 succeeded, 127 failed, 0 up-to-date, 0 skipped ==========`) compilation I have still problem with running test 
`c:\ACETAO657\ACE_wrappers\TAO\orbsvcs\tests\Security\MT_IIOP_SSL>run_test.pl
ERROR: Cannot Spawn: <.\.\server.EXE> not found
ERROR: server returned -1`

**Comment by KamilSoko** [comment]
Thank you for yours assistance.
Output from tests is the same as I had during initialization of my server:
`c:\ACETAO657\ACE_wrappers\TAO\orbsvcs\tests\Security\MT_BiDir_SSL>run_test.pl
TAO (500|8568) Unable to load protocol <SSLIOP_Factory>, No such file or directory
(500|8568) EXCEPTION, Caught exception:
system exception, ID 'IDL:omg.org/CORBA/INITIALIZE:1.0'
TAO exception, minor code = 0 (ORB Core initialization failed; unspecified errno), completed = NO`

**Comment by mitza-oci** [comment]
Is your `PATH` set up to locate all dynamic libraries required, including `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` (or equivalents for 32-bit) from OpenSSL?

**Comment by KamilSoko** [comment]
Thanks! That was it in case of tests. Unfortunately I have still problem with initialization of server but now when I know that compilation is OK maybe I will be able to figure it out. Thanks for help. Please, do not close this issue until monday (I will not be able to do changes on server until monday).

**Comment by KamilSoko** [comment]
Thanks for help!
However, now i have another problem. The server looks OK when I start it with .exe but when i try to start it as a service there is still problem with SSLIOP_Factory (I assume that when I start server as a service it cannot load openSsl libraries). Have you seen something similar before?

**Comment by mitza-oci** [comment]
Check that the current working directory and the PATH for the service process are set to what it requires.  This seems like it's not an ACE issue if it's working as a non-service process.

**Comment by KamilSoko** [comment]
The issue was related to specific user permissions (there was different account with privileges to use crypto libs).
Anyway, I have one more question. In older versions of ACETAO there was possibility to get the remote IP address by using: 
`CORBA::String_var rhost (tc->remote_host());
 retVal.HostName = rhost.in();`

However, right now (after commit 5e7f934bc11298f4ce3a8cb20e378d45528fcde7) it is impossible to get the remote hostname with this function when SSLIOP is used (NoContext exception is thrown).

My question is - is it possible to get remote hostname with usage of SSLIOP? and if it is, how can I do it?

**Comment by KamilSoko** [comment]
Thanks everyone for help! Issue solved
