### ISSUE TITLE
Remove Visual Studio 2015 azure pipeline setup

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/ACE_TAO#1033]
On March 23, 2020 the Azure Pipelines vs2015-win2012r2 hosted image will be removed, after that date we need to remove that configuration from our azure-pipelines.yml files

**Comment by jwillemsen** [comment]
https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

**Comment by mitza-oci** [comment]
Fixed by #1051
