### ISSUE TITLE
rpmbuild fails when using "skip_make" feature

### ISSUE THREAD

**Issue by egleston** [DOCGroup/ACE_TAO#1041]
### Version

6.5.5

### Host machine and operating system

CentOS 7 - 1908

### Compiler name and version (including patch level)

gcc 4.8.5-39

### The problem effects:

rpmbuild using the _skip_make_ feature.

### Synopsis

The _Building list of headers_ section of the `%install` from the `rmbuild/ace-tao.spec` file is missing a variable definition.

### Description

The _Building list of headers_ block of code fails silently and the only way to build the RPM is to start over. This makes the _skip_make_ feature unusable.

It looks like the `%{inline}` variable definition is not invoked using the _skip_make_ feature. To compile the list of headers, there is a `|| true` that catches all the errors. Since `%{inline}` is not defined, rpmbuild doesn't expand it and passes the `%{inline}` to g++ which throws an error. The error shows up in `rawhdrs.log`, but it can be hard to locate.

### Repeat by

```
rpmbuild -tb ACE+TAO-src-6.5.5.tar.gz
mv $HOME/rpmbuild/BUILD/ACE_wrappers $HOME/rpmbuild/BUILD/ACE_wrappers-BUILT
rpmbuild -tb ACE+TAO-src-6.5.5.tar.gz \
         --defines 'skip_make 1'

```

### Sample fix/ workaround
Workaround:
```
rpmbuild -tb ACE+TAO-src-6.5.5.tar.gz \
         --defines 'skip_make 1' \
         --defines 'inline -D__SKIP_MAKE_INVOKED__'
```

Fix: I added a line in the `%if %skip_make` section to the `ace-tao.spec` that ensures `%{inline}` is defined:
```
834a835
> %define inline -D__SKIP_MAKE_INVOKED__
```

**Comment by jwillemsen** [comment]
Thanks for your report, why not define inline as nothing so that %{inline} expands to nothing? Can you open a pull request with a fix that refers to this issue?
