### ISSUE TITLE
Tests fail to compile on MacOS, need Clang workaround enabled

### ISSUE THREAD

**Issue by mouse07410** [DOCGroup/ACE_TAO#1042]
### Version

Current master

### Host machine and operating system

iMac Pro running MacOS Mojave 10.14.6

### Compiler name and version (including patch level)

Clang from Xcode-11.3.1.

### The $ACE_ROOT/ace/config.h file

```
$ cat !!:$
cat ACE_TAO/ACE/ace/config.h
#include "ace/config-macosx.h"
$ 
```

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

```
$ cat ACE_TAO/ACE/include/makeinclude/platform_macros.GNU 
CCFLAGS += -std=c++11
optimize = 0
xerces3=1
INSTALL_PREFIX=/Users/ur20980/OpenDDS
include $(ACE_ROOT)/include/makeinclude/platform_macosx.GNU
$ 
```

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

```
$ cat ACE_TAO/ACE/bin/MakeProjectCreator/config/default.features 
no_cxx11=0
ssl=1
no_rapidjson=0
xerces3=1
java=1
qt5=1
openssl11=1
no_opendds_security=0
$ 
```

### AREA/CLASS/EXAMPLE AFFECTED:

All of them

### The problem effects:

Compilation

### Synopsis

Fails to compile, requires CLANG workaround.

### Sample fix/ workaround

This is how you fix it:
```patch
diff --git a/ACE/tests/Compiler_Features_32_Test.cpp b/ACE/tests/Compiler_Features_32_Test.cpp
index a7374894..f51b9e16 100644
--- a/ACE/tests/Compiler_Features_32_Test.cpp
+++ b/ACE/tests/Compiler_Features_32_Test.cpp
@@ -45,7 +45,7 @@ A::u_type_::~u_type_ ()
 void A::clear ()
 {
 #if defined __clang__ && \
-    (defined __apple_build_version__ && __apple_build_version__ < 9100000 \
+    (defined __apple_build_version__ && __apple_build_version__ <= 11000033 \
      || __clang_major__ <= 9)
 #define CLANG_WORKAROUND
 #endif
```

**Comment by jwillemsen** [comment]
Please open a pull request with the necessary fix

**Comment by mouse07410** [comment]
Done - see https://github.com/DOCGroup/ACE_TAO/pull/1043
