### ISSUE TITLE
Instantaneous timeouts when time jumping to past

### ISSUE THREAD

**Issue by tstaig** [DOCGroup/ACE_TAO#1053]
### Version

ACE+TAO-6.4.3

### Host machine and operating system
Red Hat Enterprise Linux with Kernel 3.10.0-862.xvb601.x5650.el7.x86_64 #1 SMP PREEMPT

### Target machine and operating system (if different from host)
Red Hat Enterprise Linux with Kernel 3.10.0-862.xvb601.x5650.el7.x86_64 #1 SMP PREEMPT

### Compiler name and version (including patch level)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)

### The $ACE_ROOT/ace/config.h file

If you use a link to a platform-specific file, simply state which one

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

platform_linux_common.GNU

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Used by MPC when you generate your own makefiles

### AREA/CLASS/EXAMPLE AFFECTED:

The area of failure is in ACE's Countdown_Time_T class.

### The problem effects:

It affects execution, in the sense that CORBA calls that generate a timeouts right way, even though there should be time left for it to finish.

### Description

We have in the system a synchronization mechanism with a Maser or an NTP service (Simulation mode), which means that the OS time is being altered all the time. Long time ago we modified this mechanism so the OS time alterations would only be done forward (we forcefully slowed down the CPU clocks using '/usr/sbin/tickadj 9998'). This is not ideal due to various reasons, so we used some of our time investigating the issue. The elapsed time is being evaluated in very small windows of time in the ace/Countdown_Time_T.cpp file, which has a very small chance of triggering a timeout due to the change in the operating system date/time to the past.

This is, when an "elapsed time" window is negative.

### Repeat by

It is quite complicated to reproduce the issue, even in production this is something that happens several days apart. The elapsed time is being evaluated in very small windows of time, which means that the time has to jump back just after the current time has been evaluated...

### Sample fix/ workaround

What we did was the following change:
```
diff -Naur TAO.org/ACE_wrappers/ace/Countdown_Time_T.cpp TAO/ACE_wrappers/ace/Countdown_Time_T.cpp
--- TAO.org/ACE_wrappers/ace/Countdown_Time_T.cpp       2017-04-20 04:52:06.744646655 -0300
+++ TAO/ACE_wrappers/ace/Countdown_Time_T.cpp   2018-09-12 09:48:27.283589158 -0300
@@ -45,8 +45,8 @@
       ACE_Time_Value const elapsed_time =
           this->time_policy_ () - this->start_time_;

-      if (elapsed_time >= ACE_Time_Value::zero &&
-          this->max_wait_value_ > elapsed_time)
+      //Removed check of negative elapsed time.
+      if (this->max_wait_value_ > elapsed_time)
         {
           *this->max_wait_time_ = this->max_wait_value_ - elapsed_time;
         }
```
We've been using this in production for more than 2 years now, protecting us from the issue and not resulting in any side effect, at least not that we've been able to identify.

**Comment by jwillemsen** [comment]
Have you enabled monotonic time support in ACE? See https://htmlpreview.github.io/?https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/docs/ACE-monotonic-timer.html for an overview of its features.

For TAO you have to enable monotonic time support, in your ace/config.h you could add to the top the following lines to let TAO use monotonic time support
```
#define TAO_USE_HR_TIME_POLICY_STRATEGY
#define ACE_HAS_CLOCK_GETTIME_MONOTONIC
```

**Comment by jwillemsen** [comment]
When there was a max wait time of 1 second and the time is changed 1 hour back during the wait period with your change the max wait time is changed to about 1 hour which doesn't seem correct to me.

To correctly handling time corrections you should enable the monotonic time support at the TAO level.

**Comment by jwillemsen** [comment]
With your change a wait of 1 second at the moment we travel back 1 hour in time results in a wait of 1 hour and 1 second, that could cause other major issues for a system (see https://github.com/DOCGroup/ACE_TAO/commit/cb403b627316e1afa2433c416729e6ed3ab8bd00 for when the check got added). 

When your system can experience a time correction you should enable the monotonic time policy so that a way of 1 second is always 1 second, independent of the time shift.

**Comment by tstaig** [comment]
Hi Johnny, thanks for your feedback, we have now done as you suggest in this comment to configure the monotonic time support for ACE. Initially this has worked in our simulation environments.

Sadly, due to the pandemic, we have been postponing these tests and even now that tests have been performed for regressions and in our simulation environment, we still have our observatory's main system turned off until further notice.

I just write here to notify that we have seen no problems introduced by using the monotonic clock, so it seems to be the correct approach to use. I will update the information once we get the time to test this in the production environment and we actually set this to be the default timing mechanism in our system.

Thanks again for your help!

**Comment by jwillemsen** [comment]
Good to hear that this helped, monotonic time is the solution for this. Hopefully you can test this in production soon.
