### ISSUE TITLE
Visual Studio 2019 16.5 internal compiler error when building ACE

### ISSUE THREAD

**Issue by mitza-oci** [DOCGroup/ACE_TAO#1059]
https://developercommunity.visualstudio.com/content/problem/954522/internal-compiler-error-1925286104.html

Hopefully no change required to ACE, but I'm filing it here in case anyone else runs into it.

**Comment by jwillemsen** [comment]
Thanks @mitza-oci for reporting this to Microsoft and shared the link here. Microsoft already confirmed the bug!

**Comment by jwillemsen** [comment]
https://github.com/actions/virtual-environments/issues/605

**Comment by jwillemsen** [comment]
Latest 16.5.4 still has this bug

**Comment by esohns** [comment]
16.5.5 still produces an ICE

**Comment by mitza-oci** [comment]
> 
> 
> 16.5.5 still produces an ICE

Based on what I saw in the "developer community" page (see link above), I think we don't expect a fix until 16.6.  I haven't tried the preview of that release yet, if anyone has a chance to try it please report your results here.

**Comment by jwillemsen** [comment]
See #1114 for a change in ACE that fixed the internal error on my dev station

**Comment by SkyFire** [comment]
Compiles fine with the preview release.

**Comment by jwillemsen** [comment]
Just merged a change to ACE that resolved this internal compiler error

**Comment by jwillemsen** [comment]
Fixed in the 16.6 compiler version which got released today
