### ISSUE TITLE
AIX 6.1 ACE building process not working

### ISSUE THREAD

**Issue by Marf97** [DOCGroup/ACE_TAO#1060]
### Version

ACE 6.5.0

### Host machine and operating system

AIX 6.1

### Compiler name and version (including patch level)

gcc version 8.1.0

### The $ACE_ROOT/ace/config.h file

config-aix-5.x.h

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

platform_aix_g++.GNU

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Don't have this file at all

### AREA/CLASS/EXAMPLE AFFECTED:

Compilation/build of ACE fails

### The problem effects:

ACE itself is affected. Can't compile it at all.

### Synopsis

I need to build new version of ACE for my project and I encountered some compilation problems. After some time of trying to make sure I'm fitting conditions decsribed in manual:
http://www.dre.vanderbilt.edu/~schmidt/DOC_ROOT/ACE/ACE-INSTALL.html#unix
I'm not really sure what to do now and maybe you can tell me whether it's bug or my fault.

### Description

My problem is quite simple yet fundamental to be able to work with ACE. Following the process at the website above my GNU `make` is version 4.2.1, set my  $ACE_ROOT filled in both `ace/config.h` and `include/makeinclude/platform_marcros.GNU`. Also I had problems with `rpath` so I tried to disable it by adding `install_rpath=0`. Then I tried to make ACE and this is the result:
```
bash-4.2# make
make[1]: Entering directory '/home/tst/ACE_wrappers/ace'
GNUmakefile: /home/tst/ACE_wrappers/ace/GNUmakefile.ACE MAKEFLAGS=w
make[1]: Leaving directory '/home/tst/ACE_wrappers/ace'
make[1]: Entering directory '/home/tst/ACE_wrappers/ACEXML/common'
GNUmakefile: /home/tst/ACE_wrappers/ACEXML/common/GNUmakefile.ACEXML MAKEFLAGS=w
.... (make text that is too long)
make[1]: Leaving directory '/home/tst/ACE_wrappers/apps/gperf/src'
make[1]: Entering directory '/home/tst/ACE_wrappers/apps/gperf/tests'
GNUmakefile: /home/tst/ACE_wrappers/apps/gperf/tests/GNUmakefile.m3inset MAKEFLAGS=w
g++ -Wnon-virtual-dtor -O2  -pthread -DACE_AIX_VERS=601 -maix32 -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -DACE_HAS_CUSTOM_EXPORT_MACROS=0   -I/home/tst/ACE_wrappers -D__ACE_INLINE__ -I../../..  -Wl,-brtl -L/home/tst/ACE_wrappers/lib -L.  -L../../../lib  -o m3out .obj/modula3.o .obj/test.o -lACE -lxti -ldl
ld: 0711-317 ERROR: Undefined symbol: .in_word_set(char const*, unsigned int)
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
make[1]: *** [GNUmakefile.m3inset:196: m3out] Error 1
make[1]: Leaving directory '/home/tst/ACE_wrappers/apps/gperf/tests'
make: *** [GNUmakefile:1241: m3inset] Error 2
```
Most of the ACE builds OK but I have specific problem with `gperf` which I don't know why is included because I don't need TAO to be honest. When I try to run without `install_rpath=0` I get problems with it and don't know how to solve them.

Second part is when I tried to specify my INSTALL_PREFIX and run `make install`  I get to completely another type of error:
```
bash-4.2# make install
make[1]: Entering directory '/home/tst/ACE_wrappers/ace'
GNUmakefile: /home/tst/ACE_wrappers/ace/GNUmakefile.ACE MAKEFLAGS=w
perl -ne'if (/^#END MPC-Generated Install Info/) {exit 0}' \
  -e'elsif (/^#BEGIN MPC-Generated Install Info/) {$ok=1}' \
  -e'elsif ($ok && s/^#//) {print}' GNUmakefile.ACE | \
/home/tst/ACE_wrappers/MPC/prj_install.pl -i -s lib_output,header_files,template_files,inline_files,installdata_files \
  -b header_files=include/ace -b template_files=include/ace -b inline_files=include/ace -o lib_output=lib -x installdata_files -b installdata_files=share/ace   \
  MY INSTALL_PREFIX PATH
/bin/sh[4]: /home/tst/ACE_wrappers/MPC/prj_install.pl:  not found.
make[1]: *** [GNUmakefile.ACE:525: install] Error 127
make[1]: Leaving directory '/home/tst/ACE_wrappers/ace'
make: *** [GNUmakefile:31: install] Error 2
```
I was checking the `prj_install.pl` and path is OK and my install_prefix is also existing (checking is as I'm writing this one).

To provide more info my version of `ld` is 1.65.1.14

If you can provide me info on how to build ACE on AIX it would be nice but only thing there is the UNIX building steps which I tried to follow. 

### Repeat by

I'm using link mentioned above to make a build.

**Comment by mitza-oci** [comment]
I can't speak for the other companies who are supporting ACE, but here at [OCI](https://objectcomputing.com) we used to regularly run AIX builds.  Due to costs of maintenance and low client interest, we no longer regularly run these builds.  However, we can set up a build on demand if needed.

For these particular issues I'd suggest building only libACE:
```
cd $ACE_ROOT/ace
make ACE
make -f GNUmakefile.ACE install
```
And for `prj_install.pl` check that the script is executable.

**Comment by Marf97** [comment]
Trying out your suggestions but with no success... I have tried to build only libACE. `make ACE` went OK.

When I try to do `make -f GNUmakefile.ACE install` I still get same problems like I said above. 

- With `install_rpath=0` I get problems with perl script `prj_install.pl` that is not found. I tried to make it executable.
- Without  `install_rpath=0` I get problems with linker and tells me it doesn't recognize that flags.

**Comment by shuston** [comment]
Riverace, likewise, has not had customer demand for AIX in some time. The machines are still in my garage though if anyone wants to buy them and crank it up.

You don’t need gperf, so you can ignore those errors.

The rpath install has probably not been tested in quite some time.

-Steve

**Comment by Marf97** [comment]
It was said on website I don't need gperf but I was following commands there so it was building gperf for me also...

Any idea what I can do with rpath problems?

> Riverace, likewise, has not had customer demand for AIX in some time. The machines are still in my garage though if anyone wants to buy them and crank it up. You don’t need gperf, so you can ignore those errors. The rpath install has probably not been tested in quite some time.

**Comment by jwillemsen** [comment]
Can you try to edit `ace/GNUmakefile.ACE` and before `/home/tst/ACE_wrappers/MPC/prj_install.pl` add `perl `, so explicitly execute perl, maybe that helps?

**Comment by Marf97** [comment]
> Can you try to edit `ace/GNUmakefile.ACE` and before `/home/tst/ACE_wrappers/MPC/prj_install.pl` add `perl `, so explicitly execute perl, maybe that helps?

Seems like it helped to run `make install` part OK. Thank you a lot! :) Nonetheless I probably still encountering some other problems. I'm not working right now just tried tu run it (it's late for me now).

**Comment by mitza-oci** [comment]
> Any idea what I can do with rpath problems?

Run the linker directly from the shell with a modified command line adapted to this platform.  Then report here what changes were necessary and we can bring them in to the platform configuration files.

**Comment by jwillemsen** [comment]
Closing, please open a new pull request when you have fixes for ACE on AIX
