### ISSUE TITLE
Invocation_Adapter::get_stub returns nil in TAO 2.5.10 release but doesn't in TAO 2.5.0 release

### ISSUE THREAD

**Issue by edmh007** [DOCGroup/ACE_TAO#1164]
Problem Report Form:
------------------------------------------------------------------------------------------------------------------------>
To: ace-bugs@list.isis.vanderbilt.edu
Subject: Invocation_Adapter::get_stub returns nil in TAO 2.5.10 release

    ACE VERSION: 6.5.10

    HOST MACHINE and OPERATING SYSTEM: Linux ( Fedora 32 distro )
 
    TARGET MACHINE and OPERATING SYSTEM, if different from HOST:
    COMPILER NAME AND VERSION (AND PATCHLEVEL): gcc (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)

    THE $ACE_ROOT/ace/config.h FILE [if you use a link to a platform-
    specific file, simply state which one]: config-linux.h

    THE $ACE_ROOT/include/makeinclude/platform_macros.GNU FILE [if you
    use a link to a platform-specific file, simply state which one
    (unless this isn't used in this case, e.g., with Microsoft Visual
    C++)]:  platform_linux.GNU

    CONTENTS OF $ACE_ROOT/bin/MakeProjectCreator/config/default.features
    (used by MPC when you generate your own makefiles): not applicable

    AREA/CLASS/EXAMPLE AFFECTED:
      See details below 

    DOES THE PROBLEM AFFECT: EXECUTION 
 
    SYNOPSIS:
       I moved from ACE 6.5.0 ( TAO 2.5.0 ) to ACE 6.5.10 ( TAO 2.5.10 ).
       Now my application gets the following error:
       "Invocation_Adapter::get_stub, raising CORBA::INTERNAL because of nil stub."
       This happens when calling _non_existient

    DESCRIPTION:
        See SYNOPSIS.
        Note:  If I drop back to 6.5.0/2.5.0 ( after patching for deprecated stropts.h removal) my application works fine.

    REPEAT BY:
       Move from 6.5.0/2.5.0 to 6.5.10/2.5.10

    SAMPLE FIX/WORKAROUND: drop all the way back to 6.5.0/2.5.0

**Comment by jwillemsen** [comment]
Are you 100% sure that only x.5.10 ACE/TAO dlls are loaded? Have you tried to enable TAO ORB logging to see what happens, maybe set also ACE_DEBUG=1 as environment to see which DLL's are loaded?

**Comment by edmh007** [comment]
200% sure.

Purged system of all .so files from x.5.0  release of ACE+TAO.

Enabling logging provides nothing useful ( at least to me ).

Here is the output at the point where object->_non_existient is called:

  "Invocation_Adapter::get_stub, raising CORBA::INTERNAL because of nil
stub."

Note that a call to _narrow  on the object was successful.

Also observed this:

"TAO (536002|536002) - No protocol proxy in _get_policy"

**Comment by jwillemsen** [comment]
Without detailes logs we can’t assist you further, please attach them

**Comment by edmh007** [comment]
In order to get logs, I decided to build a simple test program using just the IDL that has the problem.
But!  it works there so I must have a conflict in my production application which uses a mix of CORBA and DDS.   We recently upgraded the DDS too ...   very odd.     I guess you can close this issue.

**Comment by jwillemsen** [comment]
At the moment you found the cause, please add it here so that others can maybe have benefit of that
