### ISSUE TITLE
Compile ACE+TAO x.5.11 fail on parametermodec.h(47): fatal error C1189: #error:  This file should be regenerated with TAO_IDL

### ISSUE THREAD

**Issue by KamilSoko** [DOCGroup/ACE_TAO#1252]
Hi,

I am trying to compile ACE+TAO x.5.11 and it's finish with fatal error: `parametermodec.h(47): fatal error C1189: #error:  This file should be regenerated with TAO_IDL`.
Could you give me any advice why it is happening and how to resolve this error (what does it mean to regenerate it with TAO_IDL)?
I think it's generated during compilation but somehow with wrong version?
`31>Invoking "..\..\bin\tao_idl on ParameterMode.pidl"
31>tao-idli_rDdrG7.cpp
31>Invoking "..\..\bin\tao_idl on PI_Forward.pidl"
31>tao-idli_zGIwlx.cpp
31>Invoking "..\..\bin\tao_idl on Policy.pidl"
31>tao-idli_jFwpNH.cpp
31>Invoking "..\..\bin\tao_idl on Policy_Current.pidl"
31>tao-idli_fqzQky.cpp
31>Invoking "..\..\bin\tao_idl on Policy_Forward.pidl"
31>tao-idli_j1mRtX.cpp
31>Invoking "..\..\bin\tao_idl on Policy_Manager.pidl"
31>tao-idli_wrLNuL.cpp
31>Invoking "..\..\bin\tao_idl on PortableInterceptor.pidl"
31>tao-idli_5yAIBM.cpp
31>Invoking "..\..\bin\tao_idl on Services.pidl"
31>tao-idli_E9EOqT.cpp
31>Invoking "..\..\bin\tao_idl on ShortSeq.pidl"
31>tao-idli_n40k9G.cpp
31>Invoking "..\..\bin\tao_idl on StringSeq.pidl"
31>tao-idli_sq6cIr.cpp
31>Invoking "..\..\bin\tao_idl on TAO.pidl"
31>tao-idli_0Iz9qg.cpp
31>Invoking "..\..\bin\tao_idl on TimeBase.pidl"
31>tao-idli_cXtXhd.cpp
31>Invoking "..\..\bin\tao_idl on ULongLongSeq.pidl"
31>tao-idli_1IHRfb.cpp
31>Invoking "..\..\bin\tao_idl on ULongSeq.pidl"
31>tao-idli_k5uJ1l.cpp
31>Invoking "..\..\bin\tao_idl on UShortSeq.pidl"
31>tao-idli_o8jii6.cpp
31>Invoking "..\..\bin\tao_idl on WCharSeq.pidl"
31>tao-idli_rQgnyG.cpp
31>Invoking "..\..\bin\tao_idl on WStringSeq.pidl"
31>tao-idli_odQfuu.cpp
60>------ Build started: Project: TAO, Configuration: Debug Win32 ------
60>Abstract_Servant_Base.cpp
60>Acceptor_Filter.cpp
60>Acceptor_Registry.cpp
60>d:\ace+tao-6.5.11\ace_wrappers\tao\tao\parametermodec.h(47): fatal error C1189: #error:  This file should be regenerated with TAO_IDL`

and the file contains:
`#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 8
#error This file should be regenerated with TAO_IDL
#endif`

Thanks in advance for any help.
BR

**Comment by jwillemsen** [comment]
It means that you `tao_idl` version doesn't match the source tree you are compiling, could it be that there is a different tao_idl on your path? What is the output of `tao_idl -V` and what is the content of your `ACE_wrappers/TAO/tao/Version.h` file?

**Comment by jwillemsen** [comment]
I now see that the output is there, the tao_idl you are using is 2.5.8 which should be 6.5.11, check your path/settings where the old tao_idl version is coming from

**Comment by KamilSoko** [comment]
Thanks for pointing the problem, I have not cleared all paths from previous compilation.
I will close this issue.
Thanks again for quick response and help.
