### ISSUE TITLE
Cleanup ACE_Auto_Ptr

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/ACE_TAO#1378]
Should remove ACE_Auto_Ptr and use std::unique_ptr instead

**Comment by ClausKlein** [comment]
see https://github.com/DOCGroup/ACE_TAO/pull/1589

**Comment by jwillemsen** [comment]
Done, last cleanup part of https://github.com/DOCGroup/ACE_TAO/pull/2226
