### ISSUE TITLE
Incorrect usage of the commands `\param` and `@param`  in documentation

### ISSUE THREAD

**Issue by albert-github** [DOCGroup/ACE_TAO#1449]
### Version

This is a documentation problem with the version 7.0.0 but probably also in older versions.

### The problem effects:

Does it affect compilation, linking, or execution. Please indicate whether ACE/TAO, your application, or both are affected.

### Synopsis

Incorrect usage of the commands `\param` and `@param` 

### Description

In the file: https://github.com/DOCGroup/ACE_TAO/blob/master/TAO/tao/Profile_Transport_Resolver.h we see around line: 181
```
/**
     * If current effective policies cause the invocation to raise
     * CORBA::INV_POLICY exception, the conflicting/problematic policies
     * are stored in this list.  This is used by \param
     * Object::_validate_connection method to inform clients about
     * causes of invocation failure.
     * @par
     * Conflicting policies are only stored in this list if \param
     * init_inconsistent_policies method has been called prior to the
     * beginning of invocation.  This saves extra work of conflicting
     * policies 'logging' when it's not needed.
     ...
```
resulting in (see http://www.dre.vanderbilt.edu/Doxygen/7.0.0/html/libtao-doc/a07031.html#a6f65523c13f665cfecde88fcb14d0e3d):

![inconsistent_policies_](https://user-images.githubusercontent.com/5223533/110779966-78cd6800-8264-11eb-9281-844631a947dc.png)

in the file: https://github.com/DOCGroup/ACE_TAO/blob/master/TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Endpoint.h we see around the line 228:
```
      /**
       * Return true if this endpoint is equivalent to @param
       * other_endpoint.
       * Two synthetic endpoints are equivalent if their iiop counterparts are
       * equivalent, and, if both have non-zero ssl ports, their ssl
       * ports are the same.
       */
```
which will give a similar problem.

In both cases this isn't the intended use of the `param` command and in the warnings file there will be warnings about this.

**Comment by jwillemsen** [comment]
Please open a pull request with the proposed changes

**Comment by albert-github** [comment]
I'm not a ACE / TAO user but found this problem with checking some doxygen problems (with the help of Fossies, see e.g. https://fossies.org/dox/ACE+TAO-src-7.0.0/ ).
I try to solve the problems that are in doxygen, so I'd like to leave the reported changes to ACE / TAO developer / users.

**Comment by jwillemsen** [comment]
When you are purely interested in doxygen, run https://github.com/DOCGroup/ACE_TAO/blob/9fe32b45a01b5d9b453d03902f986aca65292761/ACE/bin/generate_doxygen.pl and look at the output, there are some internal inconsisties reported. Y doxygen itself

**Comment by albert-github** [comment]
I'm definitely interested!!
I would like to run the script to see what errors are reported so we might be able to improve doxygen but a small quick start so that I'm able to run the script I see that some environment variables have to be set, but setting ACE_ROOT to ACE is not sufficient, as I get warnings like `warning: tag INPUT: input source 'ace/os_include' does not exist`.

Note I see that you used 1.9.0 I would advise to use 1.9.1 (release about 10 days after 1.9.0) as in the 1.9.0 version there were some serious problems (see https://www.doxygen.nl/manual/changelog.html).

**Comment by jwillemsen** [comment]
See https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/docs/bczar/bczar.html for the doxygen steps as I run them with a release

**Comment by albert-github** [comment]
Thanks. I assume you refer to the bottom part of the point 13. I did a quick run

Would have been nice when I could have easily used my own doxygen executable as the default executable on the system I used was a 1.8.18 version.  So I modified:
- `ACE/bin/generate_rel_manpages` setting `doxy_path` to my own executable
- `bin/generate_doxygen.pl` the `open` statement for doxygen with the full path

Setup of doxygen
- `COLS_IN_ALPHA_INDEX` has become obsolete as of doxygen 1.9.0, I would remove it from the used `Doxyfile`s
- `warning: argument 'a4wide' for option PAPER_TYPE is not a valid enum value
    Using the default: a4!`. I would adjust the used Doxyfile`s

I see quite a few warning messages
-   `no matching class member for ...`
    Something that most likely has to be improved on the doxygen side
- `... ACE_TAO/ACE/ace/Service_Repository.cpp:619: warning: reached end of file while inside a 'code' block!`
   Something to be fixed by ACE / TAO incorrect usage of `@code` at line 512 of the mentioned file:
   ` * Return a ptr to the entry in @code ps. There is no locking so make`
   This has probably the same problem as this reason for this issue and it looks like it is at other laces as well.
-  `warning: Unsupported xml/html tag <...> found`
    This is something that should be fixed by ACE / TAO, or do you have another solution
-  `error: Internal inconsistency: namespace in IDL not module, library or constant group`
   Probably a problem on the doxygen side, should be investigated
   Probably `..ACE_TAO/ACE/html/libtao-doc/TAO.tag:1: error: Internal inconsistency: namespace in IDL not module, library or constant group` is a direct consequence of this
- `The following parameters of ... are not documented:`
  This is something that should be fixed by ACE / TAO
- `.../ACE_TAO/ACE/ace/Based_Pointer_Repository.h:67: warning: explicit link request to 'include' could not be resolved`
   i.e. `/// order to avoid circular #include dependencies.`
   This is something that should be fixed by ACE / TAO `probably some backticks will do wonders


So far some of my observations.

**Comment by jwillemsen** [comment]
>     * `COLS_IN_ALPHA_INDEX` has become obsolete as of doxygen 1.9.0, I would remove it from the used `Doxyfile`s

I have doxygen 1.9.1 on my system on which I generate the release docu, so we should upgrade this

>     * `... ACE_TAO/ACE/ace/Service_Repository.cpp:619: warning: reached end of file while inside a 'code' block!`
>       Something to be fixed by ACE / TAO incorrect usage of `@code` at line 512 of the mentioned file:
>       ` * Return a ptr to the entry in @code ps. There is no locking so make`
>       This has probably the same problem as this reason for this issue and it looks like it is at other laces as well.

We have a huge code base going back a long time, in time we switched to doxygen but it could be that there are wrong tags and issues to be fixed, any pull requests are welcome ;-)

>     * `error: Internal inconsistency: namespace in IDL not module, library or constant group`
>       Probably a problem on the doxygen side, should be investigated
>       Probably `..ACE_TAO/ACE/html/libtao-doc/TAO.tag:1: error: Internal inconsistency: namespace in IDL not module, library or constant group` is a direct consequence of this

Yes, that are the ones I meant, that looks something to investigate further at the doxygen side

**Comment by jwillemsen** [comment]
Created a PR with the upgrade of the doxygen files and a change to some headers to fix the doxygen usage
