### ISSUE TITLE
logging strategy doesn't rotate file 

### ISSUE THREAD

**Issue by normalscene** [DOCGroup/ACE_TAO#1516]
### Version
ACE 6.5.12
The version of ACE and/or TAO you are using

### Host machine and operating system
Ubuntu 20.04

### Target machine and operating system (if different from host)
Ubuntu 20.04

### Compiler name and version (including patch level)
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.2.0-5ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-WJNXnb/gcc-10-10.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-WJNXnb/gcc-10-10.2.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Ubuntu 10.2.0-5ubuntu1~20.04) 
```

### The $ACE_ROOT/ace/config.h file
Using the standard config.h for gnu c++ provided by ACE distribution

If you use a link to a platform-specific file, simply state which one

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file
I am using the standard one for linux GNU.

if you use a link to a platform-specific file, simply state which one (unless this isn't used in this case, e.g., with Microsoft Visual C++)

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features
```
saturn@rings:/opt/mystuff/cpp-frameworks/ACE/6.5.12/ACE_wrappers/ace$ cat $ACE_ROOT/bin/MakeProjectCreator/config/default.features
cat: /opt/mystuff/cpp-frameworks/ACE/6.5.12/ACE_wrappers/bin/MakeProjectCreator/config/default.features: No such file or directory
saturn@rings:/opt/mystuff/cpp-frameworks/ACE/6.5.12/ACE_wrappers/ace$ 

```
Don't think I have this file in my system

Used by MPC when you generate your own makefiles

### AREA/CLASS/EXAMPLE AFFECTED:
Logging strategy example, as specified in the book, is not working as expected.
Not sure what is it that I am doing wrong. Below is the example program being used
along with the svc.conf being used.

Sample Program Source file.

```
#include <ace/Log_Msg.h>
#include <ace/Service_Config.h>

[[noreturn]] int ACE_TMAIN (int argc, ACE_TCHAR *argv[])
{
    if (ACE_Service_Config::open (argc,
                                  argv,
                                  ACE_DEFAULT_LOGGER_KEY,
                                  1,
                                  0,
                                  1) < 0)
        ACE_ERROR_RETURN ((LM_ERROR, ACE_TEXT ("%p\n"),
                ACE_TEXT ("Service Config open")),
                          1);
    ACE_TRACE ("main");

    while (true) {
        ACE_DEBUG ((LM_NOTICE, ACE_TEXT ("%D:%M: %t%IHowdy Pardner\n")));
        ACE_DEBUG ((LM_INFO, ACE_TEXT ("%D:%M: %t%IGoodnight\n")));
        ACE_DEBUG ((LM_DEBUG, ACE_TEXT ("%D:%M: %t%IGoodnight\n")));
        ACE_OS::sleep(ACE_Time_Value(0,20 * 1000));
    }
}
// Listing 1
```

Corresponding "svc.conf" config file being used.
`dynamic Logger Service_Object * ACE:_make_ACE_Logging_Strategy() "-i2 -m25 -N2 -s logging_strategy.log -fSTDERR|OSTREAM -pINFO|~DEBUG"`

What example failed?  What module failed to compile?

### The problem effects:
The problem doesn't impact any compilation/linking but only execution.
The log file is not rotating as expected. I am not sure where the problem lies.
The example I am trying out is just a plain vanilla example from the APG book.

Does it affect compilation, linking, or execution. Please indicate whether ACE/TAO, your application, or both are affected.

### Synopsis
I have tried many times but I was unable to figure out why the logfile doesn't rotate after the specified size has been reached.
All required configuration (as per the APG book) has been supplied but it still doesn't work. I need the log file to rotate after
the specified size has been reached.

Brief description of the problem

### Description
The service object creates the logging strategy and I can see that the logging strategy actually works as per the svc.conf provided but the log rotation and log file deletion feature(s) are not yet working for reasons unknown. I am not able to figure out why and I need some guidance on the matter.

The supplied example program along with the provided conf file should be able to reproduce the issue and if not, please let me know immediately.

Detailed description of problem.  Don't just say "<blah> doesn't work, here's a fix," explain what your program does to get to the <blah> state.

### Repeat by
Can be repeated by using the above provided sample program and its corresponding config file.
Just place the 'svc.conf' where the binary is and you should see that as soon as the size is beyond 25kb,
the logfile doesn't rotate.

What you did to get the error; include test program or session transcript if at all possible.

### Sample fix/ workaround

If available

**Comment by jwillemsen** [comment]
In order for the logging strategy to work you have to run the ACE reactor somewhere in your application, see https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/tests/Logging_Strategy_Test.cpp for a unit tests that demonstrates the logging strategy

**Comment by normalscene** [comment]
Hello @jwillemsen - Thanks for your hint - I got it working fine after spawning the reactor - but same thing, when deployed in a docker container, doesn't work. I believe the logging rotation functionality is independent of where the application is deployed - is that understanding correct?

I ensured that I am not writing the log file(s) at a path which doesn't exist. I would really like this to work and I am willing to troubleshoot this but I don't know where to begin - any hint on that please ? Many thanks in advance.
