### ISSUE TITLE
TAO generated code doesn't compile on OSX 

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/ACE_TAO#1525]
After extending the github CI action with the IDL_Test (see https://github.com/DOCGroup/ACE_TAO/pull/1524) it demonstrates that TAO generated code doesn't compile on OSX, initially reported as https://github.com/RemedyIT/taox11/issues/156

**Comment by mitza-oci** [comment]
We used to have automated builds on macOS with Apple's clang version.  It seems like it shouldn't be difficult unless things have diverged that much.

**Comment by jwillemsen** [comment]
When this issue gets resolved also enable the IDL_Test on MacOSX github action CI, see https://github.com/DOCGroup/ACE_TAO/blob/f0c83f789a58d8bff1934283fc105b887c16ef90/.github/workflows/macosx.yml#L69. This issue is very likely related to versioned namespaces
