### ISSUE TITLE
ACE 7.0.2 FreeBSD build

### ISSUE THREAD

**Issue by Viste** [DOCGroup/ACE_TAO#1529]
### Version
7.0.2 ACE

### Host machine and operating system
`FreeBSD bsd.hostname.com 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
`
### Target machine and operating system (if different from host)
`FreeBSD bsd.hostname.com 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
`
### Compiler name and version (including patch level)

```
gmake --version                                                                                                                                         Wed Jun  2 06:44:50 2021
GNU Make 4.3
Built for amd64-portbld-freebsd13.0
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

```
### The $ACE_ROOT/ace/config.h file

```
#include "ace/config-freebsd.h"
```

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

```
INSTALL_PREFIX = /usr
include $(ACE_ROOT)/include/makeinclude/platform_freebsd.GNU
```

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Used by MPC when you generate your own makefiles

### AREA/CLASS/EXAMPLE AFFECTED:

ACE

### The problem effects:

ACE

### Synopsis

just want build lib but get stuk on build error https://paste2.org/I7PntfOZ

### Description

just want build lib but get stuk on build error https://paste2.org/I7PntfOZ

### Repeat by
download ACE source from https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-7_0_2/ACE-7.0.2.zip set up environment like here described http://www.dre.vanderbilt.edu/~schmidt/DOC_ROOT/ACE/ACE-INSTALL.html#unix

https://paste2.org/xjsy6F0Y

**Comment by jwillemsen** [comment]
Be aware support on github is **best effort**, when you require a guaranteed response consider hiring one of the [commercial companies](https://github.com/DOCGroup/ACE_TAO/wiki/ACE-and-TAO-Commercial-support) who provide support and services for ACE/TAO.

FreeBSD is not a regularly used platform, very likely `ace/config-freebsd.h` needs to be updated with additional defines due to changes in FreeBSD.

**Comment by Viste** [comment]
i try to slove this myself if i have some results i need to post it here or open PR?

**Comment by iguessthislldo** [comment]
You should open a PR with the changes you needed to make.

**Comment by jwillemsen** [comment]
Closing, please open a PR
