### ISSUE TITLE
Several security tests fail

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/ACE_TAO#1623]
Following security tests seem to fail on master and on ace6tao2 branch

TAO/orbsvcs/DevGuideExamples/Security/ParticipatingApp  
TAO/orbsvcs/DevGuideExamples/Security/PolicyControllingApp  
TAO/orbsvcs/DevGuideExamples/Security/SecurityUnawareApp  
TAO/orbsvcs/tests/Security/Big_Request  
TAO/orbsvcs/tests/Security/Bug_1107_Regression  
TAO/orbsvcs/tests/Security/Callback  
TAO/orbsvcs/tests/Security/Crash_Test  
TAO/orbsvcs/tests/Security/Null_Cipher  
TAO/orbsvcs/tests/Security/Secure_Invocation

**Comment by mitza-oci** [comment]
When we've seen this before it's been due to a certificate expiring.

**Comment by jwillemsen** [comment]
Very likely a certificate issue
