### ISSUE TITLE
Add build support for Windows UWP

### ISSUE THREAD

**Issue by tuduongquyet** [DOCGroup/ACE_TAO#1645]
Please add build support for Windows UWP so UWP Apps can use ACE

**Comment by jwillemsen** [comment]
See https://github.com/microsoft/vcpkg/blob/d2019e507caf9469d8d5c93bfcd3f6d26548ca12/ports/ace/portfile.cmake#L111 how vcpkg builds ACE with vcpkg, if more is needed please open a pull request with the necessary changes or see https://github.com/DOCGroup/ACE_TAO/wiki/ACE-and-TAO-Commercial-support for the various support options
