### ISSUE TITLE
TAO_UIPMC_Endpoint does not fully support IPv6

### ISSUE THREAD

**Issue by nickwilliams-zaxiom** [DOCGroup/ACE_TAO#1683]
### Version

The version of ACE and/or TAO you are using

TAO 2.5.5 ... we are in the process of upgrading to 3.0.x, but looking through the code, this problem has not been solved there yet, either.

### Host machine and operating system

macOS 10.15
macOS 11.0
Windows 10
Windows Server 2016
RHEL 7
RHEL 8
CentOS 7
Ubuntu 20.04

### Compiler name and version (including patch level)

GCC 8.3
Apple clang version 12.0.0
Visual Studio 2016
Visual Studio 2019

### The $ACE_ROOT/ace/config.h file

n/a

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

n/a

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

n/a

### AREA/CLASS/EXAMPLE AFFECTED:

- `TAO_UIPMC_Endpoint`
- `ACE_INET_Addr`

### The problem effects:

`TAO_UIPMC_Endpoint::object_addr` calls `ACE_INET_Addr::get_ip_address`, which logs an error that the IP address is IPv6 instead of IPv4.

### Synopsis

`TAO_UIPMC_Endpoint::object_addr` calls `ACE_INET_Addr::get_ip_address`, so if you call `object_addr` on a multicast Endpoint targeting to an IPv6 address, an error gets logged that the IP address is IPv6 instead of IPv4.

### Description

`ACE_INET_Addr` is a class that officially supports IPv6; however, its method `get_ip_address` logs the following error when called on an instance representing IPv6:
>ACE_INET_Addr::get_ip_address: address is a IPv6 address not IPv4

Furthermore, `TAO_UIPMC_Endpoint::object_addr` calls `ACE_INET_Addr::get_ip_address`, so if you call `object_addr` on a multicast Endpoint targeting an IPv6 address, that error gets logged. 

This doesn't appear to actually _break_ anything (although it's possible we haven't just observed the breakage yet). Our application appears to be working. However, the logged error is nonetheless an item of concern for our end users when seen in the logs.

### Repeat by

Create an application using a multicast Endpoint that targets an IPv6 address, then get a multicast group `Object_var` with `clientORBvar->string_to_object( clientMulticastEndpoint.in() )`, which calls `TAO_IOR_Parser::parse_string`, which calls `TAO_UIPMC_Endpoint::object_addr`, which calls `ACE_INET_Addr::get_ip_address`, which logs that error.

### Sample fix/ workaround

None, other than commenting out that error log in `ACE_INET_Addr::get_ip_address` and recompiling. I've examined the latest code in trunk/3.0.3, and it hasn't changed in a way that would eliminate this issue.

**Comment by jwillemsen** [comment]
The error in `ACE_INET_Addr::get_ip_address` looks correct to me, it looks UIPMC needs some updates for ipv6

**Comment by nickwilliams-zaxiom** [comment]
Yes, that was my impression, too. However, I do wonder if `ACE_INET_Addr::get_ip_address` needs to be deprecated and replaced with something that works with both IPv4 and IPv6. It doesn't seem valid to me that `ACE_INET_Addr`, which supports IPv6, would have a method that performs this operation but only on IPv4 addresses. That said, I don't fully understand the implications of that; you would better.
