### ISSUE TITLE
tao_idl fails to compile const double variable assignments with math

### ISSUE THREAD

**Issue by eliotlyon** [DOCGroup/ACE_TAO#1713]
### Version

ACE+TAO 6.5.15 & 7.0.4

### Host machine and operating system

Red Hat Enterprise Linux 8.4

### Compiler name and version (including patch level)

gcc 8.4.1 20200928 (Red Hat 8.4.1-1)

### The $ACE_ROOT/ace/config.h file

config-linux.h

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

platform_linux.GNU

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

(doesn't exist.  I used release tarballs downloaded from this github)

### AREA/CLASS/EXAMPLE AFFECTED:

tao_idl

### Synopsis

6.5.15's and 7.0.4's tao_idl do not compile IDL that 6.5.9's tao_idl accepted

### Description

I compiled ACE+TAO 7.0.4, installed it to /tmp/ACE-7.0.4, and set up paths appropriately.  Then I ran commands as below:
```
user@box /tmp/test $ cat minimal.idl
module Minimal
{
    const double a = 6.0;
    const double b = 3.0;
    const double div = a / b;
    const double mul = a * b;
    const double add = a + b;
    const double sub = a - b;
};
user@box /tmp/test $ tao_idl minimal.idl
Error - /tmp/ACE-7.0.4/bin/tao_idl: "minimal.idl", line 5: coercion failure (Can not dump this type) to double
Error - /tmp/ACE-7.0.4/bin/tao_idl: "minimal.idl", line 6: coercion failure (Can not dump this type) to double
Error - /tmp/ACE-7.0.4/bin/tao_idl: "minimal.idl", line 7: coercion failure (Can not dump this type) to double
Error - /tmp/ACE-7.0.4/bin/tao_idl: "minimal.idl", line 8: coercion failure (Can not dump this type) to double
tao_idl: minimal.idl: found 4 errors
```

Commenting out lines 5-8 causes the compilation to succeed.

I compiled ACE 6.5.15 and its tao_idl behaves the same way.

The ACE+TAO 6.5.9 tao_idl accepts this IDL file and generates reasonable code.

**Comment by mitza-oci** [comment]
Not sure it matters, but change the end of the module to `};` (this is different in IDL than the corresponding C++ feature)

**Comment by iguessthislldo** [comment]
I did try to refactor the code in `ast_expression.cpp` that evaluates expressions in #840, so I might have accidentally broken something. I will take a look at it.

**Comment by eliotlyon** [comment]
> Not sure it matters, but change the end of the module to `};` (this is different in IDL than the corresponding C++ feature)
My mistake.  It's present in the actual file but I omitted it from the example originally.

**Comment by iguessthislldo** [comment]
I started playing around with it and float has the same problem. I also made it so the error message is a tad bit more useful:

```
Error - tao_idl: "1713/expr.idl", line 4: coercion failure (Can not dump none) to double
Error - tao_idl: "1713/expr.idl", line 5: coercion failure (Can not dump none) to double
Error - tao_idl: "1713/expr.idl", line 6: coercion failure (Can not dump none) to double
Error - tao_idl: "1713/expr.idl", line 7: coercion failure (Can not dump none) to double
Error - tao_idl: "1713/expr.idl", line 13: coercion failure (Can not dump none) to float
Error - tao_idl: "1713/expr.idl", line 14: coercion failure (Can not dump none) to float
Error - tao_idl: "1713/expr.idl", line 15: coercion failure (Can not dump none) to float
Error - tao_idl: "1713/expr.idl", line 16: coercion failure (Can not dump none) to float
```

**Comment by iguessthislldo** [comment]
Okay, so it is a result of #840 like I feared, but the existing code is passing something to my code that causes the problem, and I don't know why it's doing it this way. The main issue is that here: 

https://github.com/DOCGroup/ACE_TAO/blob/0bfb484a3635dcc293eb2c3367fd52da05722596/TAO/TAO_IDL/ast/ast_expression.cpp#L2338-L2378

floating point types result in `EK_const` getting passed to here in the place where the operations are happening:

https://github.com/DOCGroup/ACE_TAO/blob/0bfb484a3635dcc293eb2c3367fd52da05722596/TAO/TAO_IDL/ast/ast_expression.cpp#L1739-L1740

`eval_kind_to_expr_type` is something I added to simplify the code. It can't handle `EK_const` though, because it doesn't make it clear what type to actually use. I'm working on trying to modify it so that it passes more reasonable values in.

**Comment by mitza-oci** [comment]
Does the `switch (t)` need a case for `EV_double`?

**Comment by jwillemsen** [comment]
TAOX11 generates the following, so we don't calculate anything within the IDL compiler

```
namespace Minimal
{

  // generated from StubHeaderWriter#visit_const
  /// @copydoc const.idl::Minimal::a
  constexpr double a {6.0};

  // generated from StubHeaderWriter#visit_const
  /// @copydoc const.idl::Minimal::b
  constexpr double b {3.0};

  // generated from StubHeaderWriter#visit_const
  /// @copydoc const.idl::Minimal::div
  constexpr double div = (::Minimal::a / ::Minimal::b);

  // generated from StubHeaderWriter#visit_const
  /// @copydoc const.idl::Minimal::mul
  constexpr double mul = (::Minimal::a * ::Minimal::b);

  // generated from StubHeaderWriter#visit_const
  /// @copydoc const.idl::Minimal::add
  constexpr double add = (::Minimal::a + ::Minimal::b);

  // generated from StubHeaderWriter#visit_const
  /// @copydoc const.idl::Minimal::sub
  constexpr double sub = (::Minimal::a - ::Minimal::b);
} // namespace Minimal
```
