### ISSUE TITLE
not working executables with mingw64

### ISSUE THREAD

**Issue by yuryfdr** [DOCGroup/ACE_TAO#1742]
### Version

7.0.5

### Host machine and operating system

MINGW64_NT-6.3-9600 hors 3.2.0-340.x86_64 2021-08-02 16:30 UTC x86_64 Msys

### Compiler name and version (including patch level)
$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-11.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Rev2, Built by MSYS2 project)

### The $ACE_ROOT/ace/config.h file

#define ACE_HAS_VERSIONED_NAMESPACE 1
#include "ace/config-windows.h"

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

INSTALL_PREFIX = /usr/local
INSTALL_LIB = lib64
stl=1
qt5=1
ace_qt5reactor=1
tao_qtresource=1
fl=0
gl=1
ssl=0
xerces=1
xerces3=1
include $(ACE_ROOT)/include/makeinclude/platform_mingw32.GNU

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features
i turn on features above
Used by MPC when you generate your own makefiles

### AREA/CLASS/EXAMPLE AFFECTED:
./tests
$ perl run_test.pl
auto_run_tests: tests/ACE_Test
Error: ACE_Test  FAILED with exit status 127 after Time:1s

auto_run_tests_finished: tests/ACE_Test  Time:1s Result:127
Error: No log file (log/ACE_Test.log) is present
auto_run_tests: tests/Aio_Platform_Test
Error: Aio_Platform_Test  FAILED with exit status 127 after Time:0s

auto_run_tests_finished: tests/Aio_Platform_Test  Time:0s Result:127
Error: No log file (log/Aio_Platform_Test.log) is present
auto_run_tests: tests/Arg_Shifter_Test
Error: Arg_Shifter_Test  FAILED with exit status 127 after Time:0s

auto_run_tests_finished: tests/Arg_Shifter_Test  Time:0s Result:127
Error: No log file (log/Arg_Shifter_Test.log) is present
auto_run_tests: tests/ARGV_Test
Error: ARGV_Test  FAILED with exit status 127 after Time:0s

### The problem effects:

make[1]: Entering directory '/d/work202x/Projects/DepsMingw/ACE_wrappers/TAO/tao/PI'

GNUmakefile: /d/work202x/Projects/DepsMingw/ACE_wrappers/TAO/tao/PI/GNUmakefile.PI_Idl MAKEFLAGS=w

../../../bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I ../.. -Sa -St -DGEN_IDL_MAKE_DEPS -Wb,versioning_begin=TAO_BEGIN_VERSIONED_NAMESPACE_DECL -Wb,versioning_end=TAO_END_VERSIONED_NAMESPACE_DECL -SS -Sci -Gp -Gd -Wb,export_macro=TAO_PI_Export -Wb,export_include=tao/PI/pi_export.h -iC tao/PI -Sorb -GX -Wb,unique_include=tao/PI/PI.h PI_include.pidl
make[1]: *** [GNUmakefile.PI_Idl:198: PI_includeC.h] Error 127
make[1]: Leaving directory '/d/work202x/Projects/DepsMingw/ACE_wrappers/TAO/tao/PI'
make: *** [GNUmakefile:539: PI_Idl] Error 2

### Synopsis
not working executables with mingw64

### Description
I try to build ACE for mingw64, ACE build seams ok. but tao_idl.exe not work.
strange executables, that fail with 127 (seams sigsegv) produced 

(vc2019 compile TAO on the same machine without problems)

### Repeat by
i try first use included GNUMekefiles, then after failure try generate it with mwc,pl - same results

**Comment by jwillemsen** [comment]
There is a github action for MinGW64, have you checked that one? That does build and it looks tao_idl runs there, we don't test with MinGW in general due to lack of sponsoring.

**Comment by jwillemsen** [comment]
See https://buildlogs.remedy.nl/win_mingw64_64_tao/index.html for our build with MinGW64 that works

**Comment by jwillemsen** [comment]
See https://github.com/RemedyIT/taox11/blob/master/docs/src/windows_instructions.adoc#installing-build-tools-for-mingw-w64 for the TAOX11 instructions for MinGW, what we document there does work for us

**Comment by yuryfdr** [comment]
hm. i'll try your toochain.

**Comment by yuryfdr** [comment]
> See https://github.com/RemedyIT/taox11/blob/master/docs/src/windows_instructions.adoc#installing-build-tools-for-mingw-w64 for the TAOX11 instructions for MinGW, what we document there does work for us

this toolchain works.

**Comment by jwillemsen** [comment]
Good to hear that it works, from what I remember we did try multiple MinGW toolchains in the past, the ones documented with [TAOX11](https://www.taox11.org) are the ones we did validate the last time.

**Comment by yuryfdr** [comment]
I solve this problem with msys2 and windows prior 10. 
i add "LIBS += advapi32 user32" to platform_mingw32.GNU and all works fine.
(when i build unpatched ACE under win10 and then copy to win7 i have the same problem as described in the first post: message like this "CreateProcessAsUserA not fond in kernel32.dll".
after patching all works fine.
