### ISSUE TITLE
Static build does not work on Linux/Ubuntu

### ISSUE THREAD

**Issue by pierrebizz** [DOCGroup/ACE_TAO#1747]
This bug was first reported for the vcpkg build at https://github.com/microsoft/vcpkg/issues/21525

From ACE+TAO-7.0.5.tar.gz

ACE_TAO 7.0.5 Linux/Ubuntu
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

tar xzf ACE+TAO-src-7.0.5.tar.gz
cd ACE_wrappers
export ACE_ROOT=pwd
export TAO_ROOT=$ACE_ROOT/TAO
cd $ACE_ROOT/ace
ln -s config-linux.h config.h
cd $ACE_ROOT/include/makeinclude
ln -s platform_linux.GNU platform_macros.GNU
cd $TAO_ROOT
perl $ACE_ROOT/bin/mwc.pl -features "ssl=1,openssl11=1" -static -type gnuace TAO_ACE.mwc
make ssl=1 -j1

fails when it tries to build tao_idl
[out.txt](https://github.com/DOCGroup/ACE_TAO/files/7737062/out.txt)

I went back in time in the vcpkg project and the last build that worked was 6.5.12;

**Comment by mitza-oci** [comment]
Using the `-static` command line argument to `mwc.pl` is different than enabling static libraries when you run `make`.

Our automated builds use `make static_libs_only=1` (or actually by writing this into platform_macros.GNU, but it's the same) as documented in `ACE-INSTALL.html` under "Makefile Flags".

Try removing `-static` from `mwc.pl` and adding `static_libs_only=1` to `make`.
