### ISSUE TITLE
Problem with vcpkg - pkgconfig

### ISSUE THREAD

**Issue by pierrebizz** [DOCGroup/ACE_TAO#1750]
### Version

7.0.5

### Host machine and operating system
x64-Linux
### Compiler name and version (including patch level)
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

### The $ACE_ROOT/ace/config.h file
#include "ace/config-linux.h"

If you use a link to a platform-specific file, simply state which one

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU

if you use a link to a platform-specific file, simply state which one (unless this isn't used in this case, e.g., with Microsoft Visual C++)

### AREA/CLASS/EXAMPLE AFFECTED:

vcpkg install ace[tao,ssl] --triplet x64-linux fails with:

CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):
  /bin/pkg-config --exists TAO_CosProperty_Serv failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "/home/bizz/vcpkg/packages/ace_x64-linux/lib/pkgconfig:/home/bizz/vcpkg/packages/ace_x64-linux/share/pkgconfig:/home/bizz/textml/vcpkg_installed/x64-linux/lib/pkgconfig:/home/bizz/textml/vcpkg_installed/x64-linux/share/pkgconfig"
      output: Package TAO_PortableServer_Skel was not found in the pkg-config search path.

  Perhaps you should add the directory containing
  `TAO_PortableServer_Skel.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'TAO_PortableServer_Skel', required by 'TAO_CosProperty_Serv', not
  found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  buildtrees/versioning_/versions/ace/1801922b3e4808edcd0b55b6a800bbb1c01687a6/portfile.cmake:434 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)

### Sample fix/ workaround

There seems to be a problem with the dependencies specified in two .pm.in files; the attached diff file, when applied, allows vcpkg to succeed.

If available
[ACETAO_dependencyFixed.txt](https://github.com/DOCGroup/ACE_TAO/files/7824412/ACETAO_dependencyFixed.txt)

**Comment by mitza-oci** [comment]
Please create a Pull Request for the patch you're proposing

If someone doesn't have `scripts/cmake/vcpkg_fixup_pkgconfig.cmake` available, would running `pkg-config --exists TAO_CosProperty_Serv` (assuming installing the ACE+TAO libs and setting up paths, environment, etc.) be sufficient to see the problem?

**Comment by pierrebizz** [comment]
I really don't know. Two dependencies files are modified: TAO_CosProperty_Serv and TAO_Monitor; I really don't know how the .in files are created/generated/maintained; my goal is to have vcpkg work on linux !

**Comment by mitza-oci** [comment]
> Two dependencies files are modified: TAO_CosProperty_Serv and TAO_Monitor; I really don't know how the .in files are created/generated/maintained; 

The `*.pc.in` files are in this repository.  They are not generated as far as I can tell.
During installation, `*.pc` files are generated from `*.pc.in` using `ACE/bin/ace_install_pkgconfig.pl`
