### ISSUE TITLE
Make it easier to build multiple architectures within one tree with Visual Studio

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/ACE_TAO#1756]
Currently all libs/bin get put into one directory independent on the architecture. Especially when targeting multiple visual studio configurations (debug/release/arm/win32/x64/static) it would be much easier when this can be done in one tree. All intermediate files are put into configuration specific directorys, but not the output (lib/dll/exe).

**Comment by mitza-oci** [comment]
It think it's possible to customize this with `-value_template` and/or the `user_*.mpt` files.
Release already puts executables in a subdirectory which is why the test scripts need `-ExeSubDir Release`
