### ISSUE TITLE
Compile error using g++ 11

### ISSUE THREAD

**Issue by jafl** [DOCGroup/ACE_TAO#1758]
### Version

7.0.0

### Host machine and operating system

Virtual Box on MacOS.  Fedora 35.

### Compiler name and version (including patch level)

g++ (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)

### The $ACE_ROOT/ace/config.h file

config-linux.h

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

platform_linux.GNU

### AREA/CLASS/EXAMPLE AFFECTED:

Svc_Handler

### The problem effects:

Compiling my application.

### Synopsis

Compile error 

### Description

/usr/local/include/ace/Svc_Handler.cpp:117:3: error: ‘void operator delete [](void*)’ called on pointer returned from a mismatched allocation function [-Werror=mismatched-new-delete]
  117 |   ::delete [] static_cast <char *> (obj);

**Comment by jwillemsen** [comment]
Please open a pull request with the necessary fix, due to lack of sponsoring we currently regularly with Fedora 31, later versions haven't been tested yet.

**Comment by jafl** [comment]
No special flags:
    g++ -std=c++17 -D_J_HAS_PROC -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -D_XFT_NO_COMPAT_ -I/usr/include/freetype2  -D_J_UNIX -D_J_HAS_XINERAMA -Wall -Werror -I../include -I/usr/include/freetype2 -I/usr/include/libxml2 -O2  -c -o code/JStringManager.o code/JStringManager.cpp

Adding `-Wno-mismatched-new-delete` makes the compile error disappear.  I honestly don't know any other way to fix it, because your code is correct.  The compiler simply isn't smart enough to realize it.

**Comment by jwillemsen** [comment]
Ok, so the compiler is confused, maybe try to reorder includes, that sometimes helps. If that is still the problem report it to the gcc people to check it in the compiler code.

**Comment by mitza-oci** [comment]
Do any of the ACE tests have the same problem with `-Werror`?

**Comment by jafl** [comment]
I filed this bug with g++:  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103993
