### ISSUE TITLE
PaxHeaders folders preventing MPC static solution generation

### ISSUE THREAD

**Issue by willis936** [DOCGroup/ACE_TAO#1782]
### Version

Release 7.0.6

### Host machine and operating system

Windows 10 Pro Build 19042

### Target machine and operating system (if different from host)

Same as host

### Compiler name and version (including patch level)

VS2019 v16.2.0

### The $ACE_ROOT/ace/config.h file

N/A

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

N/A

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Not present.

### AREA/CLASS/EXAMPLE AFFECTED:

N/A

### The problem effects:

Issue running .mwc scripts to generate static solutions.

### Synopsis

I follow this guide using strawberry perl (5.32.1.1-64bit-portable):

https://theaceorb.com/support/faq.html#Building-GeneratingStaticProjectFiles

The script fails to run because of PaxHeaders folders.

### Description

```
ace_xtreactor.mpc: Line 1:
ERROR: No project was defined
TAO_ACE.mwc: line 22:
ERROR: Unable to process ../ace/XtReactor/PaxHeaders/ace_xtreactor.mpc
ERROR: Unable to process: TAO_ACE.mwc
```

### Repeat by

1. Download/extract DOC Group TAO+ACE 7.0.6 onto a windows machine with strawberry perl.
2. Set ACE_ROOT, TAO_ROOT, and MPC_ROOT environment variables.
3. Launch strawberry perl and cd to %TAO_ROOT%.
4. Run `perl %ACE_ROOT%\bin\mwc.pl -type vs2019 -static -name_modifier *_vs2019_Static TAO_ACE.mwc`

### Sample fix/ workaround

This can be fixed by deleting all PaxHeaders subdirectories in ACE_ROOT:

```
cd %ACE_ROOT%
FOR /d /r . %d IN (PaxHeaders) DO @IF EXIST "%d" rd /s /q "%d"
```

**Comment by willis936** [comment]
It looks like they are present in this archive:

https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-7_0_6/ACE+TAO-7.0.6.tar.gz

but not this archive:

https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-7_0_6/ACE+TAO-7.0.6.zip

**Comment by mitza-oci** [comment]
@jwillemsen is this a release script issue?

@willis936 you can also just download the tag as-is and get a copy of MPC from https://github.com/objectcomputing/MPC

**Comment by willis936** [comment]
Thanks.  Things are working as expected with the .zip release.
