### ISSUE TITLE
ACE_Refcounted_Auto_Ptr_Rep NULL pointer assignment issue

### ISSUE THREAD

**Issue by ashaikh111** [DOCGroup/ACE_TAO#1846]
ACE version 6.3.4

Hi, 
I am new to ACE,
In the following code block, why "rep" is not assigned with "NULL" or "0" after deleting it.
is it bug, that it is not assigned with "NULL" or "0" ?

_template <class X, class ACE_LOCK> inline void
ACE_Refcounted_Auto_Ptr_Rep<X, ACE_LOCK>::detach (ACE_Refcounted_Auto_Ptr_Rep<X, ACE_LOCK>*& rep)
{
  if (rep == 0)
    return;

  if (rep->ref_count_-- == 0) {
	  delete rep;
}_

**Comment by jwillemsen** [comment]
See https://github.com/DOCGroup/ACE_TAO/discussions/1847
