### ISSUE TITLE
TAO_IDL valuetype traits not compatible with -Wb,versioning_begin

### ISSUE THREAD

**Issue by mitza-oci** [DOCGroup/ACE_TAO#1857]
When developing a change for OpenDDS, @jrw972 noticed that traits specializations generated by tao_idl `valuetype` don't seem to be in the right namespace when tao_idl is run with `-Wb,versioning_begin=...`.

I'll work on a test, but I wanted to get the issue logged first.

**Comment by mitza-oci** [comment]
Test is here:
https://github.com/mitza-oci/ACE_TAO/tree/valuetype-vn/TAO/tests/IDL_Test/Versioned_Namespace

Code generated by tao_idl doesn't compile

**Comment by mitza-oci** [comment]
Build failed in GitHub Actions
https://github.com/mitza-oci/ACE_TAO/runs/6920619569?check_suite_focus=true

**Comment by mitza-oci** [comment]
@jwillemsen is it correct that be_util.cpp's usage message has the `-Wb,versioning*` options wrapped in conditionals?
```
#if (defined (ACE_HAS_VERSIONED_NAMESPACE)      \
     && ACE_HAS_VERSIONED_NAMESPACE == 1)       \
  || (defined (TAO_HAS_VERSIONED_NAMESPACE)      \
     && TAO_HAS_VERSIONED_NAMESPACE == 1)
```

**Comment by jwillemsen** [comment]
> Wb,versioni

Doesn't look correct to me, the arguments are always there, independent of this define or not
