### ISSUE TITLE
Service_Gestalt compile error due to misspelling of unique_ptr

### ISSUE THREAD

**Issue by fan-chao** [DOCGroup/ACE_TAO#1862]
There is one Compile Error in ACE-7.0.7.
File: ACE_wrappers/ace/Service_Gestalt.cpp
Line: 947

![image](https://user-images.githubusercontent.com/10006853/174940483-32fc671f-3b7b-4f43-970f-69bd34f2ce27.png)

This is a misspelling bug.

**Comment by jwillemsen** [comment]
Please open a pull request with the fix

**Comment by mitza-oci** [comment]
Based on this issue it seems like the `ACE_USES_CLASSIC_SVC_CONF == 0` case isn't compiled in CI or scoreboard builds. @fan-chao if you're interested in this configuration please consider contributing a change to the GitHub Actions CI scripts or a new build for the scoreboard.
