### ISSUE TITLE
Syntax Error in Select_Reactor.h:48

### ISSUE THREAD

**Issue by KB3HNS** [DOCGroup/ACE_TAO#1889]
### Version

7.0.1.  Issue exists in master

### Host machine and operating system
Linux SLES15

### Target machine and operating system (if different from host)
VxWorks 7 RTP (No threads) PPC32, Static Library

### Compiler name and version (including patch level)
GCC (w/ SPE Extensions) 8.3.0

### The $ACE_ROOT/ace/config.h file
-Not applicable in this situation-  Also, this cannot be provided because it contains proprietary information.

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file
Key options:
- TOOL = gnu
- install_rpath = 0
- static_libs_only = 1
- pthread = 0
- threads = 0
- include ...platform_vxworks.GNU

_Note: We can't use the pthread scheduler due to timing constraints, instead for us, ACE is compiled without thread support_

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features
n/a

### AREA/CLASS/EXAMPLE AFFECTED:
[Select_Reactor.h:48](https://github.com/DOCGroup/ACE_TAO/blob/d799942f683eee8dafa8f81384f6a5d835ccc649/ACE/ace/Select_Reactor.h#L48)

### The problem effects:
Compile fail, syntax error, missing semicolon.

### Synopsis
See above.

### Description
Syntax error (most likely during C++11 conversion).  Semicolon missing after `default` keyword.

### Repeat by

Normal build for VxWorks RTP without thread support.

### Sample fix/ workaround

See PR below for fix.

**Comment by jwillemsen** [comment]
Please open a pull request with the fix

**Comment by KB3HNS** [comment]
@jwillemsen 
I was in process.  Sorry for delay.  My internet was being slow.

See [PR](https://github.com/DOCGroup/ACE_TAO/pull/1890)

**Comment by mitza-oci** [comment]
Consider adding a `threads=0` configuration to GitHub Actions
