### ISSUE TITLE
ACE_SSL.dll and other ACE .dll files missing file version information

### ISSUE THREAD

**Issue by wkbrd** [DOCGroup/ACE_TAO#1950]
### Version

ACE 6.5.5

### Host machine and operating system

Windows 10

### Target machine and operating system (if different from host)

Same

### Compiler name and version (including patch level)

Visual Studio 2019

### The problem effects:

ACE_SSL.dll

### Synopsis

ACE_SSL.dll and other .dll files lack version information

### Description

ACE_SSL.dll lacks File version, File description, Product name, and Product version fields, where it is filled in within ACE.dll.  Other .dll files within ACE are also missing these fields.

![image](https://user-images.githubusercontent.com/30599409/193848786-df9cdefb-2874-4f38-aa62-5a87e2734947.png)

### Repeat by

Repeatable during a build.

### Sample fix/ workaround

N/A. Look at ACE.dll to determine file version of the release.

**Comment by jwillemsen** [comment]
Fixed, #1954, thanks!
