### ISSUE TITLE
TAO has some logrotate files with invalid commands

### ISSUE THREAD

**Issue by Serban8** [DOCGroup/ACE_TAO#1981]
### Version

ACE Version     : 7.0.8
TAO Version     : 3.0.8

### Host machine and operating system

SUSE Linux Enterprise 15

### Target machine and operating system (if different from host)

Not different from host

### Compiler name and version (including patch level)

g++ (SUSE Linux) 7.5.0

### The $ACE_ROOT/ace/config.h file
```
#define ACE_HAS_IPV6
#define ACE_USES_IPV4_IPV6_MIGRATION
#include "ace/config-linux.h"
```
### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file
```
TAO_IDL = /usr/bin/tao_idl
TAO_IDL_DEP = /usr/bin/tao_idl
CCFLAGS += -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables
CFLAGS += -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables
ssl = 1
inline = 0
buildbits = 64
optimize = 1
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
```
### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features
```
ssl=1
bzip2 = 1
zlib = 1
```
### AREA/CLASS/EXAMPLE AFFECTED:

creates warnings in the log file

### The problem effects:

Problem doesn't affect compilation/linking/execution. It is just a misconfiguration in TAO.

### Synopsis

TAO has some logrotate files with invalid commands

### Description

When checking our logs I noticed the following warnings:
```
Oct 28 08:00:01 logrotate[11710]: error: tao-cosconcurrency:5 unknown option 'endscript' -- ignoring line
Oct 28 08:00:01 logrotate[11710]: error: tao-cosevent:5 unknown option 'endscript' -- ignoring line
Oct 28 08:00:01 logrotate[11710]: error: tao-cosnaming:5 unknown option 'endscript' -- ignoring line
Oct 28 08:00:01 logrotate[11710]: error: tao-cosnotification:5 unknown option 'endscript' -- ignoring line
Oct 28 08:00:01 logrotate[11710]: error: tao-costrading:5 unknown option 'endscript' -- ignoring line
Oct 28 08:00:01 logrotate[11710]: error: tao-rtevent:5 unknown option 'endscript' -- ignoring line
```

### Repeat by

`# grep -i error /var/log/messages`

### Sample fix/ workaround

Removig the "endscript" directive from the files [[here](https://github.com/DOCGroup/ACE_TAO/tree/master/ACE/rpmbuild/etc/logrotate.d)] should solve this issue.

**Comment by jwillemsen** [comment]
Please open a pull request with the necessary changes
