### ISSUE TITLE
Error building ACE on Windows 11 / VS 2019

### ISSUE THREAD

**Issue by alexchandel** [DOCGroup/ACE_TAO#2051]
### Version

7.0.11

### Host machine and operating system

Windows 11

### Compiler name and version (including patch level)

```
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The CXX compiler identification is MSVC 19.29.30148.0
```

```
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
```

### The $ACE_ROOT/ace/config.h file

```C++
#ifndef ACE_CONFIG_CUSTOM_H
#define ACE_CONFIG_CUSTOM_H

#include "ace/config-windows.h"

#endif // ACE_CONFIG_CUSTOM_H
```

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

```make
# Defaults
debug       ?= 0
optimize    ?= 1
#inline determined below, defaults to !debug
CPU         ?= X64
winnt       ?= 1
winregistry ?= 1
wfmo        ?= 1
qos         ?= 1

include $(ACE_ROOT)/include/makeinclude/platform_win32_msvc.GNU
```

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Unmodified.

### AREA/CLASS/EXAMPLE AFFECTED:

Linking ACE.

### The problem effects:

ACE fails to link.

### Synopsis / Description

Attempting to build ACE 7.0.11 on Windows (Win 11, VS 2019) fails with the following link-time error, at least when built with CMake.  [This exact case is hosted here](https://github.com/alexchandel/test-cmake-acetao).

```sh
  WIN32_Asynch_IO.cpp
  WIN32_Proactor.cpp
  XML_Svc_Conf.cpp
  XTI_ATM_Mcast.cpp
  ace_wchar.cpp
  Generating Code...
     Creating library C:/Users/Dev/Git/test-cmake-acetao/opt/ACE_wrappers/lib/ACEd.lib and object C:/Users/Dev/Git/test-cmake-acetao/opt/ACE_wrappers/lib/ACEd.exp
OS_NS_sys_socket.obj : error LNK2019: unresolved external symbol __imp_if_nametoindex referenced in function "unsigned int __cdecl ACE_OS::if_nametoindex(char const *)" (?if_nametoindex@ACE_OS@@YAIPEBD@Z) [C:\Users\Dev\Git\test-cmake-acetao\build\opt\ACE_wrappers\TAO\ace\ACE.vcxproj]
OS_NS_sys_socket.obj : error LNK2019: unresolved external symbol __imp_if_indextoname referenced in function "char * __cdecl ACE_OS::if_indextoname(unsigned int,char *)" (?if_indextoname@ACE_OS@@YAPEADIPEAD@Z) [C:\Users\Dev\Git\test-cmake-acetao\build\opt\ACE_wrappers\TAO\ace\ACE.vcxproj]
SOCK_Dgram.obj : error LNK2019: unresolved external symbol __imp_GetAdaptersAddresses referenced in function "protected: int __cdecl ACE_SOCK_Dgram::make_multicast_ifaddr(struct ip_mreq *,class ACE_INET_Addr const &,char const *)" (?make_multicast_ifaddr@ACE_SOCK_Dgram@@IEAAHPEAUip_mreq@@AEBVACE_INET_Addr@@PEBD@Z) [C:\Users\Dev\Git\test-cmake-acetao\build\opt\ACE_wrappers\TAO\ace\ACE.vcxproj]
SOCK_Dgram_Mcast.obj : error LNK2001: unresolved external symbol __imp_GetAdaptersAddresses [C:\Users\Dev\Git\test-cmake-acetao\build\opt\ACE_wrappers\TAO\ace\ACE.vcxproj]
C:\Users\Dev\Git\test-cmake-acetao\opt\ACE_wrappers\lib\ACEd.dll : fatal error LNK1120: 3 unresolved externals [C:\Users\Dev\Git\test-cmake-acetao\build\opt\ACE_wrappers\TAO\ace\ACE.vcxproj]
```

### Repeat by

A replication example is hosted [here](https://github.com/alexchandel/test-cmake-acetao). On Windows, run:

```sh
git clone https://github.com/alexchandel/test-cmake-acetao.git
cd test-cmake-acetao
mkdir build
cd build
cmake ..
cmake --build .
```

**Comment by jwillemsen** [comment]
Some cmake support was added after 7.0.11, you will need to use github master

**Comment by esohns** [comment]
missing Iphlpapi.lib ?

**Comment by alexchandel** [comment]
@jwillemsen  I am using the GitHub master of MPC to generate the CMake.  Otherwise compiling wouldn't even get this far.  Please reopen this.

**Comment by alexchandel** [comment]
@jwillemsen Are you referencing https://github.com/DOCGroup/ACE_TAO/commit/36c558c30b842c6b6f70b62a8736c35077b2f093 ?  Why is this required only for CMake builds?  How do other builds successfully link `iphlpapi` ?

**Comment by alexchandel** [comment]
Adding this to `FindAceTao.cmake` seems to fix it:
```cmake
target_link_libraries(ACE PUBLIC iphlpapi)
```

**Comment by jwillemsen** [comment]
> @jwillemsen I am using the GitHub master of MPC to generate the CMake. Otherwise compiling wouldn't even get this far. Please reopen this.

You also need master of ACE/TAO

**Comment by mitza-oci** [comment]
> Adding this to `FindAceTao.cmake` seems to fix it:
> 
> ```cmake
> target_link_libraries(ACE PUBLIC iphlpapi)
> ```

Right, we have an example of where this is functional in OpenDDS.  You could use that as the model to work from, see `cmake/OpenDDSConfig.cmake:209`
