### ISSUE TITLE
Ace Logger Crash 

### ISSUE THREAD

**Issue by Sivasundareswaran** [DOCGroup/ACE_TAO#2072]
Hi Team ,

Version :ACE-7.0.10
OS Platform :Ubuntu 22.04

I am facing crash when I passing message string which has special character (like % ) to Ace Logger .  

Please find the below details for log string and crash 

**Logger Message which has special character :**

```
23-05-22 04:43:48.787 [INFO]   Test.cpp:940  Remove Leg( %a\\\325\177) from  Map \n", '\000' <repeats 1911 times>
```

**Crash ** 

```
Core was generated by `./app'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140555360200256) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd59850e640 (LWP 636221))]
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140555360200256) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140555360200256) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140555360200256, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fd5989dd476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fd5989c37f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fd5990fe5e1 in ACE_OS::abort () at /usr/local/src/ACE_wrappers/ace/OS_NS_stdlib.inl:39
#6  ACE_Log_Msg::log (this=0x7fd590000b70, format_str=<optimized out>, log_priority=<optimized out>, argp=0x7fd59850d0f0,
    category=<optimized out>) at /usr/local/src/ACE_wrappers/ace/Log_Msg.cpp:2180
#7  0x00007fd5990ff77f in ACE_Log_Msg::log (this=<optimized out>, log_priority=<optimized out>, format_str=<optimized out>)
    at /usr/local/src/ACE_wrappers/ace/Log_Msg.cpp:938
```

Please help us to resolve this issue 
Thanks in advance .

**Comment by shuston** [comment]
Your format string includes %a. That causes an abort after formatting the string. Follow the stack trace's record of source file and line number to see the code.

**Comment by Sivasundareswaran** [comment]
Yes ,I saw that code but even through we are including %a ,this should not abort the application ,what if we want to print this kind of format in logger .

**Comment by shuston** [comment]
ACE's documented behavior is to abort after formatting a line with %a in it. If you want to avoid that you need to escape the %a sequence.

**Comment by Sivasundareswaran** [comment]
Ok thanks for the help.

**Comment by Sivasundareswaran** [comment]
escaping % from application layer is not good ,so is there any option available to make these changes in ACE lib.
because if we want print one string which has % that time crash will happen, 
so this is Ace  bug ,please share your valuable feedback to handle this situation .
