### ISSUE TITLE
Error - ..\bin\tao_idl.exe: ".\OMG\orb.idl", line 42: illegal redefinition ::CORBA::TypeCode

### ISSUE THREAD

**Issue by xpston008** [DOCGroup/ACE_TAO#2092]
ACE_TAO_6.4.7  what's causing this

execute this command 
```
.\bin\tao_idl.exe .\OMG\orb.idl  -o .\src\  -SS -Ssh 
```

tao-idli_vLTPcY.cpp
Error - ..\bin\tao_idl.exe: ".\OMG\orb.idl", line 42: illegal redefinition ::CORBA::TypeCode, ::CORBA, CORBA::TypeCode
processing .\OMG\orb.idl
..\bin\tao_idl.exe: .\OMG\orb.idl: found 1 error

orb.idl  content 
```
module CORBA
{
    interface Principal { };
    interface NamedValue { };
    interface TypeCode { };
};
```

**Comment by jwillemsen** [comment]
The `interface TypeCode` is implicitly created in tao_idl so no need to declare it again. These are all standard defined interfaces, they exist already in the TAO core, you shouldn't define them in your user IDL

**Comment by xpston008** [comment]
My guess might be so, in IDL remove Type_Code definition. Thank you
