### ISSUE TITLE
How does TAO parse Any:sequence and struct array data types?

### ISSUE THREAD

**Issue by xpston008** [DOCGroup/ACE_TAO#2096]
I'm a beginner and have been using corba(tao) recently.

When TAO parses Any sequence and struct, array data type (CORBA::TCKind::tk_sequence tk_array tk_struct), in c++, how to confirm that the "Any sequence" type is "typedef sequence<>" defined in IDL and more complex Nested "sequences"

Is it judged by this function `RepositoryId id() raises(BadKind)`

Hope you can give a piece of code or case, thank you!

**Comment by xpston008** [comment]
@jwillemsen @mitza-oci 

Looking through the information, I can't find a solution, please answer! thankyou!

**Comment by mitza-oci** [comment]
I don't think I completely understand the question.  Since you mentioned parsing an Any is this about reading an Any value from a CDR stream?  The CDR rules for Any are defined in section 9.3.5.2 of https://www.omg.org/spec/CORBA/3.4/Interoperability/PDF.

**Comment by xpston008** [comment]
@mitza-oci  thank you ! 
The problem has been solved, the purpose is to solve the Any structure analysis
