### ISSUE TITLE
cross-compile TAO fail

### ISSUE THREAD

**Issue by cxf-xiao** [DOCGroup/ACE_TAO#2101]
TAO_IDL_BE will not be built due to the following disabled make macros: build_tao_idl_be  GNUmakefile: /home/cxf/opendds/OpenDDS/build/target/ACE_wrappers/TAO/TAO_IDL/GNUmakefile.TAO_IDL_BE MAKEFLAGS=w

**Comment by jwillemsen** [comment]
That is just a warning for one of the static tao_idl projects, safe to ignore
