### ISSUE TITLE
g++error,build ACE on windows with g++

### ISSUE THREAD

**Issue by shaozhihua** [DOCGroup/ACE_TAO#2164]
at start everything goes fine,but when the link stage,error coming,
<img width="1280" alt="g++shob_error" src="https://github.com/DOCGroup/ACE_TAO/assets/18071679/043f8fda-34a0-4869-bed2-0b7d206303dd">

**Comment by shaozhihua** [comment]
I just want build opendds with mingw,so I compiled this and tao,this is my first step,.....failed at the first step,upset....

**Comment by shaozhihua** [comment]
I can not find any .shob file in anywhere.

**Comment by jwillemsen** [comment]
Adding screenshots is not helping, add always the full log as attachment. R2CORBA (see https://github.com/RemedyIT/r2corba) does use MinGW64 on Windows, the github actions there does seem to run, so it is very likely something on your system.

**Comment by shaozhihua** [comment]
I give up .I choose the greatest compiler in the universe ：Visual Studio.
what can I do,just this.
