### ISSUE TITLE
ACE_TAO is build in gcc 6 and above not in <5 gcc

### ISSUE THREAD

**Issue by navinagaraj** [DOCGroup/ACE_TAO#2190]
```
Error log:
hort, CORBA::Short)':
ACExTAO-7.1.3/ACE_wrappers/TAO/examples/Simple/grid/Grid_i.cpp:26:14: error: call of overloaded 'unique_ptr(int)' is ambiguous
     array_ (0)
```

**Comment by jwillemsen** [comment]
ACE+TAO require C++14 or newer, gcc < 5 is ancient, please upgrade your compiler. Feel free to open a pull request with a proposed fix for the example

**Comment by mitza-oci** [comment]
Have you tried the latest 6.x version?
https://github.com/DOCGroup/ACE_TAO/releases/tag/ACE%2BTAO-6_5_20

**Comment by navinagaraj** [comment]
This is the latest version right ACE+TAO-7_1_3, can explain why this version not building in gcc 5. the same version build in gcc 6 ?

**Comment by jwillemsen** [comment]
Closing, gcc 5 isn't actively maintained anymore
