### ISSUE TITLE
Broken links in ACE and TAO documentation....   $ACE_ROOT/TAO doesn't exist in github version.   $ACE_ROOT/../TAO does

### ISSUE THREAD

**Issue by broerd** [DOCGroup/ACE_TAO#2207]
### Version

7.1.3

### Host machine and operating system     
Linux  (Mint 21.1)

### Compiler name and version (including patch level)
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

### The $ACE_ROOT/ace/config.h file
include "ace/config-linux.h"

If you use a link to a platform-specific file, simply state which one

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

if you use a link to a platform-specific file, simply state which one (unless this isn't used in this case, e.g., with Microsoft Visual C++)

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Used by MPC when you generate your own makefiles

### AREA/CLASS/EXAMPLE AFFECTED:
All links seem to suggest that TAO was once a subdirectory of $ACE_ROOT.   This is not the case from github
one directory ACE, another TAO.
All the links $ACE_ROOT/TAO are broken (in the Readme HTML probably more places)

### The problem effects:

Does it affect compilation, linking, or execution. Please indicate whether ACE/TAO, your application, or both are affected.

### Synopsis

Brief description of the problem

### Description

Detailed description of problem.  Don't just say "<blah> doesn't work, here's a fix," explain what your program does to get to the <blah> state.

### Repeat by

What you did to get the error; include test program or session transcript if at all possible.

### Sample fix/ workaround

If available

**Comment by jwillemsen** [comment]
The links should work when you use a regular distribution, there TAO is a subdirectory of ACE
