### ISSUE TITLE
Does ACE(7.0.1)+TAO(3.0.1) supports SUSE15 SP5?

### ISSUE THREAD

**Issue by Sahil148024** [DOCGroup/ACE_TAO#2233]
Hi team,

We are using ACE(7.0.1)+TAO(3.0.1) in our project and we are planning to upgrade our SUSE to SUSE15 SP5.

Does ACE+TAO version mentioned above supports SUSE 15 SP5?

Appreciate your earliest response on the same as after this we can plan our activity accordingly.

Regards,
Sahil

**Comment by jwillemsen** [comment]
It hasn't been tested, @Remedy IT maintains only ACE for SLES15 without SP (see http://www.dre.vanderbilt.edu/scoreboard/integrated.html). When you need to have ACE/TAO validated for a specific platform see https://github.com/DOCGroup/ACE_TAO/wiki/ACE-and-TAO-Commercial-support for the support companies who could assist you with that, including @RemedyIT
