### ISSUE TITLE
ACE_OFF_T has different type in libACE and application

### ISSUE THREAD

**Issue by enricodarde** [DOCGroup/ACE_TAO#2268]
### Version

        7.1.2, also 8.0.0

### Host machine and operating system

         Arch Linux ARM
         A20-OLinuXino-Micro
         #uname -a
         Linux oli2 6.9.10-1-ARCH #1 SMP PREEMPT Sat Jul 20 07:56:14 MDT 2024 armv7l GNU/Linux

         
         same problem on:
         Raspbian GNU/Linux 11 (bullseye)
         Mod. B V1.1 14
         #uname -a
         Linux rpi1 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
         
         both 32Bit ARM

### Compiler name and version (including patch level)

        c++ (GCC) 14.1.1 20240507
        and 
        c++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
 

### The $ACE_ROOT/ace/config.h file

        #define ACE_MAXLOGMSGLEN 16*1024
        #define ACE_HAS_REACTOR_NOTIFICATION_QUEUE
        #define _FILE_OFFSET_BITS 64
        #include "ace/config-linux.h"
        
        same problem if _FILE_OFFSET_BITS is not set

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

        INSTALL_PREFIX = /usr/local
        include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Used by MPC when you generate your own makefiles

### AREA/CLASS/EXAMPLE AFFECTED:

        e.g. FILE_IO

### The problem effects:

        unresolved symbols at application link time referencing functions using ACE_OFF_T

### Synopsis

        ACE_OFF_T has different type in libACE and application

### Description

        The ACE library is built without problems with ACE_OFF_T as type "long long"!
        
        # nm -C /usr/local/lib/libACE.so.7.1.2 | grep truncate
                    U ftruncate64@GLIBC_2.4
            00095a94 T ACE_FILE::truncate(long long)
    
        but when building an application the executable/object file contains references
        which expect ACE_OFF_T as long, which lead to unresolved symbols
        
        The library has type "long long"  no matter if _FILE_OFFSET_BITS is set or not!

### Repeat by

        #include "ace/ACE.h"
        #include "ace/FILE_IO.h"
        #include "ace/FILE_Connector.h"

        int main(int argc, ACE_TCHAR *argv[])
        {
            char Buff[4096];
            const char FNam[]="test.txt";
            ACE_FILE_IO FIO_;
            ACE_FILE_Addr Addr_;

            Addr_.set(FNam);
            ACE_FILE_Connector Connector;
            if(Connector.connect (FIO_,
                                    Addr_,
                                    0,                 // No timeout.
                                    ACE_Addr::sap_any, // Ignored.
                                    0,                 // Don't try to reuse the addr.
                                    O_RDWR|O_CREAT,            // O_RDWR|O_CREAT,|O_APPEND ...
                                    ACE_DEFAULT_FILE_PERMS)             // ACE_DEFAULT_FILE_PERMS
                )
            {
                perror("cannot open");
                return -1;
            }
            if(-1==FIO_.send(Buff, 4096))
            { printf("cannot write"); }
                
            if(FIO_.truncate(2048) == -1)
            { printf("cannot truncate"); }
            
            ACE_OS::unlink(FNam);
        }
        
        #c++ -std=c++17 tmp.cpp -lACE
        /usr/bin/ld: /tmp/cckMk2DN.o: in function `main':
        tmp.cpp:(.text+0x178): undefined reference to `ACE_FILE::truncate(long)'
        collect2: error: ld returned 1 exit status

### Sample fix/ workaround

       in the installed ACE include directory change
       /usr/local/include/ace/os_include/sys/os_types.h
       line: typedef off_t ACE_OFF_T;
         to: typedef long long ACE_OFF_T;

**Comment by mitza-oci** [comment]
Change this command: `c++ -std=c++17 tmp.cpp -lACE` to include all the same `-D` options that ACE itself uses, along with any relevant compiler flags that change ABI

**Comment by mitza-oci** [comment]
I was not able to get the same results on Debian 11 (Bullseye)
```
# nm -C ../lib/libACE.so.8.0.1 | grep truncate\(
00000000000c2a70 T ACE_FILE::truncate(long)
```

**Comment by enricodarde** [comment]
Type long on a 64 bit system is 64 bit wide
I further use SUSE Leap on  x86_64 and Ubuntu on a ARM_64 system without problems. Seems to be it's a 32bit issue

Further investigations of my much bigger "target" app showed more ACE_OFF_T issues.
e.g. ACE_OS::lstat() failed with EOVERFLOW which means, the value st_size in the stat structure which is of type off_t is not big enough to hold the file size.
This led to the idea to define _FILE_OFFSET_BITS=64 also while compiling the application.
I reversed the change/workaround  in /usr/local/include/ace/os_include/sys/os_types.h and passed "-D_FILE_OFFSET_BITS=64" to the compiler and all built well.
Currently no further problems were observed at runtime !!!! 

I have not set this define all the years before so I suppose the information _FILE_OFFSET_BITS=64 got anyhow lost and is no more active when including ACE.h 

How is the compiler option -std=c++17 correlatetd to the -D options and their passing to the application?
If using -std=c++17 would cause the same -D options in the application, this would be the solution.
I was not aware of this effect/mechanism

**Comment by mitza-oci** [comment]
This a 32-bit ARM build without any manual override of `_FILE_OFFSET_BITS`.

```
# nm -C libACE.so | grep truncate\(
00095910 T ACE_FILE::truncate(long)
```

A simplified form of the test application uses the same symbol name:
```
# nm -C ace_test.o | grep truncate
         U ACE_FILE::truncate(long)
```

The `lstat` and _FILE_OFFSET_BITS issue should be transparent to ACE.  _FILE_OFFSET_BITS is a feature of glibc that changes its API based on the preprocessor macro.  As long as the macro is defined consistently when building ACE and using ACE it should be fine.

Adding the _FILE_OFFSET_BITS 64 line to ace/config.h results in:

```
# nm -C libACE.so | grep truncate\(
00095948 T ACE_FILE::truncate(long long)
```

and

```
# nm -C ace_test | grep truncate
         U ACE_FILE::truncate(long long)
```

**Comment by enricodarde** [comment]
What you demonstrate is what i would also expect.
But my two systems show different results.
I have compiled ACE on both systems clean from tarball again, one time with  "_FILE_OFFSET_BITS 64" set 
and the other time not set.
In both cases on both systems ACE is compiled with "-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
I could nowhere find, where these "-D" arguments come from.

There is a "/usr/include/bits/environments.h" and a "/usr/include/arm-linux-gnueabihf/bits/environments.h" (on raspian)
which defines:
#define __ILP32_OFFBIG_CFLAGS   "-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
This headers are included in "unistd.h" but "__ILP32_OFFBIG_CFLAGS" is nowhere used.
For testing, i have also changed this define without effect. 

Sorry, my example is missing a line
I had (unnecessary)
#include <iostream>"
before 
#include "ace/ACE.h"
(or any other system header e.g. unistd.h)
In this case the build fails with unresolved symbol.
When placing "#include <iostream>" after the ACE-includes, the example builds well
This is bad because the order of includes should not matter.
In a great project as special include order is hardly to achieve.
But as you mentioned with argument "-D_FILE_OFFSET_BITS=64" all builds well in both cases.


Finally i am rather unhappy with the situation for the following reasons:
- ACE does not care for "FILE_OFFSET_BITS 64" and compiles always with  
  "-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
  and I do not understand the mechanism behind, i do not know where the arguments come from.
- I do not understand the mechanism behind the fact that the include order is relevant and leads to unresolved symbols.
- Although passing -D_FILE_OFFSET_BITS=64" also at build of the application seem to solve the problem,
  i wonder how all could work properly all the years ago, where i did not pass this argument.
  Did i have a functioning include order by accident?

**Comment by mitza-oci** [comment]
Since `_FILE_OFFSET_BITS` is a glibc feature that doesn't "belong" to ACE, it's best to keep it out of `ace/config.h` and related ACE files.  Passing it as a `-D` compiler option guarantees that it's seen by all headers included in any order.

**Comment by enricodarde** [comment]
Thank you very much for your help.
It is reassuring to know that there is help here in case of trouble.
