### ISSUE TITLE
documentation uses TAO_USES_LOCAL_MEMORY_POOL in stead of TAO_USE_LOCAL_MEMORY_POOL as compile time setting

### ISSUE THREAD

**Issue by remko-duppen** [DOCGroup/ACE_TAO#2292]
nothing major, just confused me when I tried to find the default setting

**Comment by jwillemsen** [comment]
Please open a PR with a fix to the docu

**Comment by remko-duppen** [comment]
I guess I should create a branch to do that, right?

**Comment by jwillemsen** [comment]
See https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project, you can use a fork

**Comment by jwillemsen** [comment]
Fixed by https://github.com/DOCGroup/ACE_TAO/pull/2293
