### ISSUE TITLE
[Question] Multicast on macOS

### ISSUE THREAD

**Issue by francesco-romano** [DOCGroup/ACE_TAO#281]
Dear all,

I'm trying to make multicast working with ACE on macOS.
I created this simple example (https://gist.github.com/francesco-romano/5a1634aae430046b58757ea7920db16f)  which generates to simple applications: a receiver and a sender. It has been implemented both with plain BSD sockets and with ACE (you can switch by properly defining `ACE_SOCKETS`. (I've also created a simple CMakeLists to compile the example, where you can switch the two implementations. Unfortunaltey there not exist any FindAce.cmake, so you have to manually update the include and library variables)

While BSD implementation works, if I switch to ACE, I get an `errno=49`, i.e. `Can't assign requested address` as soon as I try to send a message.
Instead, if at https://gist.github.com/francesco-romano/5a1634aae430046b58757ea7920db16f#file-acesender-c-L45 I explicitly set `OPT_BINDADDR_NO` it works.

My system is macOS 10.11.6 on a quite new macbook Pro (retina).
Can you explain where is the error in my implementation?

(of course the real program is more complex than this example, but I managed to replicate the issue here)

Thanks 😄

**Comment by mitza-oci** [comment]
Please see for example how OpenDDS (which uses ACE) handles multicast on 
Mac OS X

https://github.com/objectcomputing/OpenDDS/blob/master/dds/DCPS/transport/multicast/MulticastDataLink.cpp#L94

**Comment by francesco-romano** [comment]
Thanks @mitza-oci 
That is exactly the fix I am doing in the my (complex) code, but I thought it was too simple to be correct.

Looking at the ACE code I think that the line that is changing this behaviour is https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/ace/SOCK_Dgram_Mcast.cpp#L208
as a consequence of the following line in the .h: https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/ace/SOCK_Dgram_Mcast.h#L138
This implies that `ACE_LACKS_PERFECT_MULTICAST_FILTERING` is 1 and indeed in the ace config for macOS it is set to one.
Is this correct for macOS or is it a wrong default value? 
My machine (but probably because it is a 2014 machine) supports IGMPv3 so I would expect that define to be 0. (BTW: I tried to force IGMP to version 2 but this did not change the outcome)
