### ISSUE TITLE
ace rpm in linux - unicode support ?

### ISSUE THREAD

**Issue by gadh** [DOCGroup/ACE_TAO#432]
does it built already with these options ?
```
ACE_HAS_WCHAR
ACE_USES_WCHAR
```
for example the rpms in this site, for Centos 7:
http://download.opensuse.org/repositories/devel:/libraries:/ACE:/micro/CentOS_7/x86_64/

**Comment by jwillemsen** [comment]
No, the RPMs build without ACE_USES_WCHAR, see https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/rpmbuild/ace-tao.spec for the current spec file we use on OBS. Using that spec file yu can build your own RPMs, you only have to extend it for wchar

**Comment by gadh** [comment]
thanks.
 i dont' know on which file to make a pull request since the platform_macros.GNU is not in github

**Comment by jwillemsen** [comment]
The spec file in the link above, that generates it for packaging

**Comment by jwillemsen** [comment]
Closing this isse, RPMs on OBS build without uses_wchar.
