### ISSUE TITLE
ACE_Singleton has a pointer to a lock which can be used after ACE::fini destroys that lock

### ISSUE THREAD

**Issue by mitza-oci** [DOCGroup/ACE_TAO#554]
See PR #553 for the test case.

**Comment by mitza-oci** [comment]
`ACE_Singleton<TYPE, ACE_LOCK>::instance ()` has a local static pointer `lock` which, after first use, points to an object controlled by ACE_Object_Manager.  When ACE_Object_Manager shuts down (ACE::fini), this lock is destroyed.  When singleton is used after the next ACE::init, the pointer refers to an invalid object and *depending on the lock type* is not re-initialized.

**Comment by mitza-oci** [comment]
Potential fixes:
1. in instance(), when registering for cleanup with object manager, pass &lock as the extra parameter to at_exit.  Then cleanup(void*) gets this value as the parameter and can zero it out.
2. ACE_Object_Manager::get_singleton_lock overloads for ACE_Thread_Mutex, ACE_Mutex, ACE_RW_Thread_Mutex should not check for null first (make those behave like ACE_Null_Mutex and ACE_Recursive_Thread_Mutex

**Comment by mitza-oci** [comment]
bug fix option 1
```
@@ -103,7 +103,7 @@
               ACE_NEW_RETURN (singleton, (ACE_Singleton<TYPE, ACE_LOCK>), 0);

               // Register for destruction with ACE_Object_Manager.
-              ACE_Object_Manager::at_exit (singleton, 0, typeid (TYPE).name ());
+              ACE_Object_Manager::at_exit (singleton, &lock, typeid (TYPE).name ());
 #if defined (ACE_MT_SAFE) && (ACE_MT_SAFE != 0)
             }
 #endif /* ACE_MT_SAFE */
@@ -114,11 +114,18 @@
 }

 template <class TYPE, class ACE_LOCK> void
-ACE_Singleton<TYPE, ACE_LOCK>::cleanup (void *)
+ACE_Singleton<TYPE, ACE_LOCK>::cleanup (void *param)
 {
   ACE_Object_Manager::remove_at_exit (this);
   delete this;
   ACE_Singleton<TYPE, ACE_LOCK>::instance_i () = 0;
+
+#ifdef ACE_FACE_SAFETY_BASE
+  ACE_UNUSED_ARG (param);
+#else
+  ACE_LOCK **lock = static_cast<ACE_LOCK **> (param);
+  *lock = 0;
+#endif
 }

 template <class TYPE, class ACE_LOCK> void
```

**Comment by jwillemsen** [comment]
Can we close this issue?
