### ISSUE TITLE
Ace_Log_Msg_UNIX_Syslog::convert_log_priority method has bug in conversion

### ISSUE THREAD

**Issue by noga001** [DOCGroup/ACE_TAO#558]
Ace_Log_Msg_UNIX_Syslog::convert_log_priority method in Log_Msg_UNIX_Syslog.cpp assigns:
**syslog_priority = LOG_DEBUG**,  instead of : **syslog_priority = LOG_DEBUGGING**,  resulting in assigning a string instead of an int value.

**Comment by jwillemsen** [comment]
Please open a pull request with the necessary fix
