### ISSUE TITLE
TAO_IDL annotations: lexing/parsing separation of responsibilities

### ISSUE THREAD

**Issue by mitza-oci** [DOCGroup/ACE_TAO#571]
@okellogg related to #567, SunCC's preprocessor is still showing an incompatibility with the current lexer.

Would it be possible to split out the annotation parameter syntax from the annotation token itself?  I guess the downside to that is that the parser would need to be made aware of the "application of  annotation" rule in all places where we want to support it (perhaps not all legal places for now).

This is the preprocessor output from Bug_3940_Regression:
```
#1 "test.idl"
module test {

@ unit ( "deg" )
@ range ( min = 0.0 , max = 360.0 )
typedef float angle_t ;

@ unit ( "degC" ) @ min ( - 60 ) @ max ( 100 ) typedef short temperature_t ;

struct structure {
@ key unsigned long key ;
angle_t degrees ;
temperature_t celsius ;
} ;

} ;
```

**Comment by okellogg** [comment]
bq. \[...\] SunCC's preprocessor is still showing an incompatibility with the current lexer.

I'm not sure I understand.
Are you referring to the `@ min ( - 60 )` where the `-` must be readjoined to the `60` ?
That problem would also be present in `const` declarations?

**Comment by mitza-oci** [comment]
Not, the extra spaces are legal IDL both for const and for annotation, so TAO_IDL should accept it for annotation as it already does for const.

**Comment by jwillemsen** [comment]
Looks also bcc32 classic has the same issue

```
X:\BUILD\DOC_ROOT\ACE\bin\tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I..\.. -Sa -St test.idl
C:\Users\build\AppData\Local\Temp\tao-idli_O5Dgrx.cpp:
syntax error
Error - X:\BUILD\DOC_ROOT\ACE\bin\tao_idl.exe: "test.idl", line 3: Illegal syntax following module '{' opener
```

**Comment by okellogg** [comment]
I assume you mean
http://buildlogs.remedy.nl/win_cbxe11_bcc32c_acetao_debug/2018_02_12_00_01_Full.html#section_6 ?

Is there some way you could post the preprocessed source, e.g.
`C:\Users\build\AppData\Local\Temp\tao-idli_O5Dgrx.cpp` ?

**Comment by jwillemsen** [comment]
```
#line 1 "3940.idl"
module test {

unit("deg")
range(min=0.0, max=360.0)
typedef float angle_t;

unit("degC") min(-60) max(100) typedef short temperature_t;

struct structure {
key unsigned long key;
angle_t degrees;
temperature_t celsius;
};

};
```

**Comment by mitza-oci** [comment]
The preprocessor stripped out the `@` characters?  That's going to be harder to work with.  One option would be to use a different preprocessor with this compiler.  Or make the annotation processing optional and inject a preprocessor macro for it, so the entire test would be wrapped in `#ifdef _TAO_IDL_HAS_ANNOTATIONS`

**Comment by jwillemsen** [comment]
I reported an issue to Embarcadero hopefully they respond soon with information why they do this and whether we can disable it

**Comment by jwillemsen** [comment]
What are we going todo? Maybe just ifdef the IDL file content for suncc and borland?

**Comment by okellogg** [comment]
TBH, I still don't understand what the problem is with SunCC.
The preprocessed source attached by @mitza-oci looks as though tao_idl should be able to handle it (?)

With Borland, I agree `#ifdef`ing out is the way to go. Looks like a bug on their side and I don't see a feasible workaround.

At any rate, meanwhile I shifted the annotation handling from idl.ll to idl.ypp but still just for gracefully ignoring, no actions yet. Pull request is coming up.

**Comment by mitza-oci** [comment]
I looked into the SunCC problem in more depth.  The issue is that flex treats the first unescaped whitespace as the end of the pattern (see the ACTIONS section in http://dinosaur.compilertools.net/flex/manpage.html).  
Though possibly a moot point here, it could be fixed by making the part after the `@` a quoted string or character class.

**Comment by okellogg** [comment]
> \[...\] The issue is that flex treats the first unescaped whitespace as the end of the pattern \[...\]

Ouch, yes. Now that you say it...
I happened to stumble over that myself short before removing the pattern in idl.ll altogether.

**Comment by jwillemsen** [comment]
@okellogg Can you create a PR to disable the contents of the test IDL file for Borland?

**Comment by okellogg** [comment]
@jwillemsen I am not sure: Are we talking about adding the following in [TAO/tests/tests.mwc](https://github.com/DOCGroup/ACE_TAO/blob/master/TAO/tests/tests.mwc),

```
 // -*- MPC -*-
 workspace {
   cmdline += -include $PWD
+  exclude(borland) {
+    Bug_3940_Regression
+  }
 }

```

**Comment by jwillemsen** [comment]
No, in the IDL file add something like

#if !defined (__BORLANDC__)
#endif

**Comment by okellogg** [comment]
@jwillemsen wrote:

> I reported an issue to Embarcadero hopefully they respond soon with information why they do this and whether we can disable it

Would it be an option to use an [open source preprocessor](http://mcpp.sourceforge.net) instead of the Borland cpp32?

At [bug 2817](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2817), Jeff Parsons wrote:

> We are considering the adoption of a dedicated preprocessor for the IDL 
compiler, rather than having it use the native one, which practice has led to 
many headaches in the past similar to this one.

I believe that would be the best option.
It could also help with [bug 3933](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=3933).

**Comment by jwillemsen** [comment]
All experiments until now to integrate an open source preprocessor didn't result in something working. Most problematic is that we support platforms most other projects just ignore. 

From the side of Remedy IT we have [RILDC](https://www.remedy.nl/products/ridlc.html), maybe at some point we can find sponsoring to use RIDLC as front end and make a new backend for the IDL to C++ language mapping (we have already one for Ruby and C++11).
