### ISSUE TITLE
/usr/bin/x86_64-linux-gnu-ld: cannot find /lib: File format not recognized

### ISSUE THREAD

**Issue by jackiilong** [DOCGroup/ACE_TAO#651]
make install the latest release error

**Comment by jackiilong** [comment]
Already set LD_LIBRARY_PATH

**Comment by jwillemsen** [comment]
Please use the PROBLEM-REPORT-FORM which is in the root of the package or in the ACE directory in git.

**Comment by jwillemsen** [comment]
Closing because of lack of details
