### ISSUE TITLE
Support Clang on Android

### ISSUE THREAD

**Issue by pepijndevos** [DOCGroup/ACE_TAO#676]
Sorry for deleting all the standard questions. It's pretty simple: the Android NDK deprecates GCC, and using it gives various deprecation warnings and later compilation errors due to a broken mix of deprecated GCC stuff and new Clang stuff. These issues are marked as wontfix upstream, and GCC will be completely removed form the next release.

This library only supports GCC on Android, so Clang support is needed for compatibility with newer NDKs.

See https://github.com/DOCGroup/ACE_TAO/blob/3f3878a5639c4954bad48b036ca68cc57eb0cac2/ACE/include/makeinclude/platform_android.GNU#L235

**Comment by mitza-oci** [comment]
@iguessthislldo please update this issue when you have a change ready

**Comment by jwillemsen** [comment]
Support for clang on Android has been added by PR #726
