### ISSUE TITLE
OMG minor code (2), described as 'No usable profile in IOR.', completed = NO

### ISSUE THREAD

**Issue by guoyanzhang0817** [DOCGroup/ACE_TAO#756]
### Version
ACE 6.5.3
TAO 2.5.3
OS
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch
------------------------------------------
in file:///home/guoyanzhang/ACE_wrappers/TAO/docs/tutorials/Quoter/Event_Service/index.html
test way:
Testing

To test your changes you need to run four programs, first TAO's Naming Service:

$ $TAO_ROOT/orbsvcs/Naming_Service/tao_cosnaming -m 1

The CORBA Event Service

$ $TAO_ROOT/orbsvcs/CosEvent_Service/tao_cosevent

Now you can run your client:

$ client

and finally the server:

$ server AAAA MSFT RHAT < stock_list.txt
but on my pc show:
issue :
guoyanzhang@debian:~/ACE_wrappers/TAO$ $TAO_ROOT/orbsvcs/CosEvent_Service/tao_cosevent
(30985|140575618819904) EXCEPTION, /home/guoyanzhang/ACE_wrappers/TAO/orbsvcs/CosEvent_Service/tao_cosevent
system exception, ID 'IDL:omg.org/CORBA/TRANSIENT:1.0'
OMG minor code (2), described as 'No usable profile in IOR.', completed = NO

**Comment by jwillemsen** [comment]
This is very likely a DNS/IP issue, try to run `tao_cosevent` with `-ORBDebugLevel 10` as additional commandline arguments and look what kind for errors it gives.

Please provide all details as requested, the configuration files asked can be very important

**Comment by guoyanzhang0817** [comment]
> This is very likely a DNS/IP issue, try to run `tao_cosevent` with `-ORBDebugLevel 10` as additional commandline arguments and look what kind for errors it gives.
> 
> Please provide all details as requested, the configuration files asked can be very important

hi jwillemsen,
after I run the command "$TAO_ROOT/orbsvcs/CosEvent_Service/tao_cosevent -ORBDebugLevel 10
", I got the following information:
guoyanzhang@debian:~$ $TAO_ROOT/orbsvcs/CosEvent_Service/tao_cosevent -ORBDebugLevel 10
TAO (1873|139836832462656) - Did not find default svc.conf
TAO (1873|139836832462656) - Completed initializing the process-wide service context
TAO (1873|139836832462656) - Default ORB services initialization begins
TAO (1873|139836832462656) - ORBInitializer_Registry::register_orb_initializer 0 @0x55cae73780e0
TAO (1873|139836832462656) - ORBInitializer_Registry::register_orb_initializer 1 @0x55cae7376770
TAO (1873|139836832462656) - Default ORB services initialization completed
TAO (1873|139836832462656) - We are the default 2.5.3 ORB ...
TAO (1873|139836832462656) - Initializing the orb-specific services
TAO (1873|139836832462656) - Setting primary connection timeout hook
TAO (1873|139836832462656) - TAO_Time_Policy_Manager: loaded time policy strategy 'TAO_SYSTEM_TIME_POLICY'
TAO (1873|139836832462656) - Default_Resource_Factory - codeset manager=0x55cae7392790
TAO (1873|139836832462656) - Codeset_Manager_i::init_ccs, Loaded Codeset translator <UTF8_Latin1_Factory>, ncs = 00010001 tcs = 05010001
TAO (1873|139836832462656) - UTF16_BOM_Translator: forceBE 0
TAO (1873|139836832462656) - Loaded default protocol <IIOP_Factory>
TAO (1873|139836832462656) - Created new ORB <>
TAO (1873|139836832462656) - IIOP_Acceptor::open_i, listening on: <182.135.127.124.broad.bj.bj.static.163data.com.cn:38789>
TAO (1873|139836832462656) - TAO_System_Id_With_Unique_Id_Strategy::bind_using_system_id: type=IDL:omg.org/CosEventChannelAdmin/EventChannel:1.0, id=0x010000
TAO (1873|139836832462656) - Stub::base_profiles, acquired profile lock this = 0xe73b47d0
TAO (1873|139836832462656) - MCAST_Parser: acceptor local address 0.0.0.0:36735.

sent multicast request.
/home/guoyanzhang/ACE_wrappers/TAO/tao/MCAST_Parser.cpp; Sent multicast.# of bytes sent is 16.
multicast_query: unable to accept: Connection timed out

multicast discovery of NameService failed.
Specify -m 1 when starting Naming_Service,
or see http://www.theaceorb.com/faq/#115
for using NameService without multicast.

(1873|139836832462656) EXCEPTION, /home/guoyanzhang/ACE_wrappers/TAO/orbsvcs/CosEvent_Service/tao_cosevent
user exception, ID 'IDL:omg.org/CORBA/ORB/InvalidName:1.0'
TAO (1873|139836832462656) - TAO_Unique_Id_Strategy::unbind_using_user_id: id=0x010000
TAO (1873|139836832462656) - Destroying ORB <>
guoyanzhang@debian:~$

**Comment by guoyanzhang0817** [comment]
> This is very likely a DNS/IP issue, try to run `tao_cosevent` with `-ORBDebugLevel 10` as additional commandline arguments and look what kind for errors it gives.
> 
> Please provide all details as requested, the configuration files asked can be very important

and what is the configuration information mentioned in your email and how do I got it?

**Comment by guoyanzhang0817** [comment]
> This is very likely a DNS/IP issue, try to run `tao_cosevent` with `-ORBDebugLevel 10` as additional commandline arguments and look what kind for errors it gives.
> 
> Please provide all details as requested, the configuration files asked can be very important

I connect the commpany's wireless network, not the cable network, it is a question?

**Comment by jwillemsen** [comment]
Looks the multicast lookup of the naming service failed, very likely this is an issue on your system. See docs/tutorials/Quoter/Naming_Service for the `-ORBInitRef` commandline option to specify the naming service in an alternate way

**Comment by guoyanzhang0817** [comment]
> Looks the multicast lookup of the naming service failed, very likely this is an issue on your system. See docs/tutorials/Quoter/Naming_Service for the `-ORBInitRef` commandline option to specify the naming service in an alternate way
i am sorry, I don't know what you mean, as this:
guoyanzhang@debian:~/ACE_wrappers/TAO/docs/tutorials/Quoter$ docs/tutorials/Quoter/Naming_Service -ORBInitRef 
bash: docs/tutorials/Quoter/Naming_Service: no such file or folder
please give me more details.
thanks.

"

**Comment by jwillemsen** [comment]
Check the example in TAO/docs/tutorials/Quoter/Naming_Service about how to use -ORBInitRef, this option is also described in TAO/docs/ORBEndpoint.html

**Comment by guoyanzhang0817** [comment]
> Check the example in TAO/docs/tutorials/Quoter/Naming_Service about how to use -ORBInitRef, this option is also described in TAO/docs/ORBEndpoint.html
-------------------------------------
hi jwillemsen,
I got the definition of the option 'ORBInitRef' in file:///home/guoyanzhang/ACE_wrappers/TAO/docs/Options.html, but I still won't use the option, as this? 
guoyanzhang@debian:~/ACE_wrappers/TAO/docs/tutorials/Quoter/Naming_Service$ ./client 
./client: error while loading shared libraries: libQuoter_Idl_Lib.so.2.5.3: cannot open shared object file: No such file or directory
guoyanzhang@debian:~/ACE_wrappers/TAO/docs/tutorials/Quoter/Naming_Service$ ./client  -ORBInitRef
./client: error while loading shared libraries: libQuoter_Idl_Lib.so.2.5.3: cannot open shared object file: No such file or directory
guoyanzhang@debian:~/ACE_wrappers/TAO/docs/tutorials/Quoter/Naming_Service$ ./server -ORBInitRef
./server: error while loading shared libraries: libQuoter_Idl_Lib.so.2.5.3: cannot open shared object file: No such file or directory
guoyanzhang@debian:~/ACE_wrappers/TAO/docs/tutorials/Quoter/Naming_Service$ 
------------------
maybe I don't understand the usage of TAO, thank you for explaining it.

**Comment by jwillemsen** [comment]
Looks you haven't set LD_LIBRARY_PATH to include $ACE_ROOT/lib now. You have to specifly the arguments for -ORBInitRef, see the docs.

Maybe better to start with a smaller example, see https://www.remedy.nl/opensource/corbapg.html which contains a basic hello world example to start with

**Comment by guoyanzhang0817** [comment]
> Looks you haven't set LD_LIBRARY_PATH to include $ACE_ROOT/lib now. You have to specifly the arguments for -ORBInitRef, see the docs.
> 
> Maybe better to start with a smaller example, see https://www.remedy.nl/opensource/corbapg.html which contains a basic hello world example to start with
----------------------------------
thanks, I really did not set LD_LIBRARY_PATH to include $ACE_ROOT/lib.
#vi ~/.bashrc
115 export ACE_ROOT=/home/guoyanzhang/ACE_wrappers
116 export LD_LIBARY_PATH=$LD_LIBRARY_PATH:$ACE_ROOT/ace:$ACE_ROOT/lib
117 export TAO_ROOT=$ACE_ROOT/TAO
118 export CIAO_ROOT=$ACE_ROOT/CIAO
119 export DANCE_ROOT=$ACE_ROOT/DANCE

**Comment by jwillemsen** [comment]
Looks also . has to be in the LD_LIBRARY_PATH (current dir)

**Comment by guoyanzhang0817** [comment]
> Looks also . has to be in the LD_LIBRARY_PATH (current dir)
----------------------------------------------
hi jwillemsen,
I  set LD_LIBRARY_PATH to include $TAO_ROOT(I guess your current dir is $TAO_ROOT),
as follows:
115 export ACE_ROOT=/home/guoyanzhang/ACE_wrappers
116 export LD_LIBARY_PATH=$LD_LIBRARY_PATH:$ACE_ROOT/ace:$ACE_ROOT/lib:$TAO_ROOT
117 export TAO_ROOT=$ACE_ROOT/TAO
118 export CIAO_ROOT=$ACE_ROOT/CIAO
119 export DANCE_ROOT=$ACE_ROOT/DANCE
then I run the two command, no issue found. I tested with ~/ACE_wrappers/TAO/tests/Hello, the results as follows.
-------------------------------------------------
step 1:
guoyanzhang@debian:~/ACE_wrappers$ /home/guoyanzhang/ACE_wrappers/TAO/orbsvcs/Naming_Service/tao_cosnaming -m 1 &
[2] 3176
guoyanzhang@debian:~/ACE_wrappers$ $TAO_ROOT/orbsvcs/CosEvent_Service/tao_cosevent &
[3] 3177
guoyanzhang@debian:~/ACE_wrappers$ (3177|140491784603456) EXCEPTION, /home/guoyanzhang/ACE_wrappers/TAO/orbsvcs/CosEvent_Service/tao_cosevent
user exception, ID 'IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0'
---------------------------------------------------
step2:
now, I have opened two new terminals,
##cd ~/ACE_wrappers/TAO/tests/Hello
first, 
guoyanzhang@debian:~/ACE_wrappers/TAO/tests/Hello$ ./server 
second,
guoyanzhang@debian:~/ACE_wrappers/TAO/tests/Hello$ ./client 
(3299|140254026389312) - string returned <Hello there!>
third,
guoyanzhang@debian:~/ACE_wrappers/TAO/tests/Hello$ ./server 
(3292|140374558684992) server - event loop finished
------------------------------------
it seems that my problem has been solved, and the problem is 
116 export LD_LIBARY_PATH=$LD_LIBRARY_PATH:$ACE_ROOT/ace:$ACE_ROOT/lib:$TAO_ROOT

thank you for your help.
