### ISSUE TITLE
ACE doesn't support openssl 1.1.1

### ISSUE THREAD

**Issue by qdztxc** [DOCGroup/ACE_TAO#772]
ACE 6.5.0 build under arch linux with openssl 1.1.1.

Build pass but program croe dump in openssl.

#0  0x00007f53ac19b31e in __strcmp_sse2_unaligned () from /usr/lib/libc.so.6
#1  0x00007f53ad0c1399 in lh_insert () from libfixapi_x64.so
#2  0x00007f53ad0a011b in OBJ_NAME_add () from libfixapi_x64.so
#3  0x00007efe52fe5c73 in ?? () from /usr/lib/libssl.so.1.1
#4  0x00007efe53c994ff in __pthread_once_slow () from /usr/lib/libpthread.so.0
#5  0x00007efe52ec3d8a in CRYPTO_THREAD_run_once () from /usr/lib/libcrypto.so.1.1
#6  0x00007efe52fe5e8d in OPENSSL_init_ssl () from /usr/lib/libssl.so.1.1
#7  0x00007efe53050d8e in ACE_SSL_Context::ssl_library_init (this=<optimized out>) at /home/xinr/ACE_wrappers/ace/SSL/SSL_Context.cpp:166
#8  0x00007efe5305148e in ACE_SSL_Context::ACE_SSL_Context (this=0x1f08b88) at /home/xinr/ACE_wrappers/ace/SSL/SSL_Context.cpp:115
#9  0x00007efe5305224b in ACE_Singleton<ACE_SSL_Context, ACE_Thread_Mutex>::ACE_Singleton (this=0x1f08b80) at /home/xinr/ACE_wrappers/ace/Cleanup.inl:5
#10 ACE_Unmanaged_Singleton<ACE_SSL_Context, ACE_Thread_Mutex>::ACE_Unmanaged_Singleton (this=0x1f08b80) at /home/xinr/ACE_wrappers/ace/Singleton.inl:15
#11 ACE_Unmanaged_Singleton<ACE_SSL_Context, ACE_Thread_Mutex>::instance () at /home/xinr/ACE_wrappers/ace/Singleton.cpp:230

**Comment by jwillemsen** [comment]
We lack details to assist you, please use the issue template and provide all details asked. Also it helps when it crashes, what is the application doing, can you make a small reproducer?

**Comment by mitza-oci** [comment]
Stack frame 2 is running a (supposedly) OpenSSL function from libfixapi_x64 so it seems you may be mixing different versions of OpenSSL in the same program.

**Comment by jwillemsen** [comment]
We lack details to help you further, closing this issue
