### ISSUE TITLE
Projection of LongLong incorrect on LP64

### ISSUE THREAD

**Issue by wkbrd** [DOCGroup/ACE_TAO#850]
### Version: 6.5.4

The version of ACE and/or TAO you are using

### The $ACE_ROOT/ace/config.h file

If you use a link to a platform-specific file, simply state which one

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

if you use a link to a platform-specific file, simply state which one (unless this isn't used in this case, e.g., with Microsoft Visual C++)

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Used by MPC when you generate your own makefiles

### AREA/CLASS/EXAMPLE AFFECTED:

IDL mapping of long long is incorrect.  It is mapping to a long rather than a long long.

### The problem effects:

Data type is not as expected, producing warnings.

### Synopsis

See https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/ace/CDR_Base.h.  
Within:
```
 #   elif ACE_SIZEOF_LONG == 8
      typedef long LongLong;
```

Data items expected to be long long, but are produced as long.  This produces warnings.

### Description

See synopsis.

### Repeat by

Use long long in an IDL definition

**Comment by iguessthislldo** [comment]
I don't think IDL mappings of integer types are guaranteed to match in name with the integer types in C++ (`long long` vs `LongLong`), only minimum required size and whether or not they are signed. Regardless it shouldn't be giving warnings about this assuming `long` and `long long` are the same size. Could you post the exact warning it's giving you?

**Comment by jwillemsen** [comment]
The IDL to C++ language mapping doesn't define the native C++ type, it is up to the implementation, you as user should use CORBA::LongLong. When you use native C++ types and pass them directly to CORBA defined operations this could lead to warnings when porting between platforms. 

The IDL to C++11 language mapping uses int64_t for a IDL LongLong (see https://www.omg.org/spec/CPP11/1.3/). TAOX11 is a CORBA implementation which supports this new language mapping.

**Comment by wkbrd** [comment]
@iguessthislldo, the warning that we are experiencing is:
`warning: format ‘%lld’ expects argument of type ‘long long int’, but argument <#> has type ‘CORBA::LongLong’ {aka ‘long int’} [-Wformat=]`

This is a warning on LP64, but not a warning on ILP32.

**Comment by jwillemsen** [comment]
ACE provides `ACE_INT64_FORMAT_SPECIFIER_ASCII` as format specifier for this, see https://github.com/DOCGroup/ACE_TAO/blob/0d43e3625a6cc25e6c66da9dae3da7e4afed53d0/ACE/ace/Basic_Types.h#L544

**Comment by wkbrd** [comment]
@jwillemsen, that worked.  Thanks for the information.
