### ISSUE TITLE
Disable Delayed Ack on Window 

### ISSUE THREAD

**Issue by pyrotimux** [DOCGroup/ACE_TAO#864]
### Version

The version of ACE and/or TAO you are using
6.2.1

### Host machine and operating system
Windows

### Compiler name and version (including patch level)
VC100

### Synopsis

Need to disable Delayed Ack on window 

### Description

I am trying to replicate a real time application on a windows computer to be able to debug easier, but I ran into issue with Delayed Ack. When sending a small chunk of packets (a lot), window doesn't ACK right away and delay it by 200 ms. Doing more research about it, I came across [`this`](https://support.microsoft.com/en-us/help/328890/new-registry-entry-for-controlling-the-tcp-acknowledgment-ack-behavior). Problem with changing the registry value is that, it will affect the whole system rather than just the application that I am working with. Is there anyway to disable delayed ACK on window system like TCP_QUICKACK from linux using setsockopt?

**Comment by jwillemsen** [comment]
This sounds more a Windows API question than a ACE question, what does the Microsoft documentation say?

**Comment by pyrotimux** [comment]
Sorry I am a little new to this. I looked through the MS doc but wasn't really able to find any mention of Delayed Ack. They did documented about setting nagle by using TCP_NODELAY on setsockopt. Also wasn't sure if I am setting them in correct places so I thought I ask here as well as [stackoverflow ](https://stackoverflow.com/questions/55034112/c-disable-delayed-ack-on-windows). Right now, I am calling setsockopt with hard coded option 12 in accept method of SOCK_Acceptor, and also tried the same thing in bind and listen of OS_NS_sys_socket.inl. 

This is how I am setting it
`::setsockopt((ACE_SOCKET) handle, IPPROTO_TCP, 12, (char *)&one, sizeof(one) );`
This throw error WSAEINVAL and when I tried
```
#if !defined (SIO_TCP_SET_ACK_FREQUENCY) 
#define SIO_TCP_SET_ACK_FREQUENCY _WSAIOW(IOC_VENDOR,23)
#endif
WSAIoctl((ACE_SOCKET) handle, SIO_TCP_SET_ACK_FREQUENCY, 0, 0, info, sizeof(info), &bytes, 0, 0);
```
throws WSAEFAULT. Although someone suggested that I input buffer. I will try that and report back about this. 

I will also ask in Win API as well, but could you please point out where I should be placing these calls?

**Comment by shuston** [comment]
Here is some background info on these two TCP capabilities: [https://www.extrahop.com/company/blog/2016/tcp-nodelay-nagle-quickack-best-practices/](https://www.extrahop.com/company/blog/2016/tcp-nodelay-nagle-quickack-best-practices/)

**Comment by pyrotimux** [comment]
Ohh just reporting back. SIO_TCP_SET_ACK_FREQUENCY does disable Delayed ACK. I was missing an input buffer. Now I just need to pin point where I should place it by eliminating it one at a time. Closing this issue now. Thanks!
