### ISSUE TITLE
ACE_INET_Addr::operator= raises SEGFAULT

### ISSUE THREAD

**Issue by esohns** [DOCGroup/ACE_TAO#906]
### Version
head
### Host machine and operating system
bug found on both (current) Windows 10 and (!) Linux (current Fedora 29) systems
### Compiler name and version (including patch level)
MSVC 2019 and gcc 8.3.1
### The $ACE_ROOT/ace/config.h file
N/A
### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file
N/A
### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features
N/A
### AREA/CLASS/EXAMPLE AFFECTED:
ACE_INET_Addr::operator=
### The problem effects:
SEGFAULT at runtime
### Synopsis
invocation of the assignment operator of ACE_INET_Addr crashes the application
### Description
ACE_INET_Addr::operator= calls into ACE_INET_Addr::set (const ACE_INET_Addr &sa) implemented in INET_Addr.cpp:192-214. The SEGFAULT is raised by line 209, in turn assignment of std::vector<union ACE_INET_Addr::ip46> 'inet_addrs_' members; in my case the 'right-hand-side' has two items, 'this' zero.
It appears that assignment of std::vector<union>s' is not fully supported by current compilers.
### Repeat by
see above
### Sample fix/ workaround
workaround: avoid ACE_INET_Addr::operator=; call ACE_INET_Addr::set() manually instead

**Comment by esohns** [comment]
in the 'Description' section, I specified 'std::vectors' of 'union's; the 'unions' didn't make it to verbatim

**Comment by jwillemsen** [comment]
Please extend one of the unit tests under ACE/tests as reproducer

**Comment by esohns** [comment]
I found the issue. It was related to the same issue described here
https://stevehuston.wordpress.com/2010/07/02/trouble-with-ace-and-ipv6-make-sure-your-config-is-consistent/
i.e. ipv6=1 setting in the MPC local.features file
