### ISSUE TITLE
ACE_OutputCDR inserts random bytes into stream

### ISSUE THREAD

**Issue by JanKalin** [DOCGroup/ACE_TAO#915]
### ACE environment

Using ACE 5.7.7 on Intel i7, Windows 7 64bit with all service packs and updates, Embarcadero C++ Builder 2010.

### The $ACE_ROOT/ace/config.h file

//#define ACE_NO_INLINE
//#define ACE_AS_STATIC_LIBS=1
#define STATIC_DEBUG
#include "ace/config-win32.h"

### The problem effects:

Execution of my application.

### Synopsis

When using ACE_OutputCDR,  random bytes are entered into the stream and thus into the ACE_Message_Block that is produced.

### Description

We are using ACE_OutputCDR to serialise objects in our application and write them to disk. The same object gets written in the main thread, immediately after creation, then copies are sent to downstream threads and to a backup thread. The binary representations written by the main thread and the backup thread differ.

This is *extremely* inconvenient, as we've started computing hashes of files, to verify the integrity of backups.

The problem turns out to be the adjust() function, called, for example, by https://github.com/DOCGroup/ACE_TAO/blob/a580273d5fc7a820ab23b1aa40faf23e97063000/ACE/ace/CDR_Stream.cpp#L500 in line https://github.com/DOCGroup/ACE_TAO/blob/a580273d5fc7a820ab23b1aa40faf23e97063000/ACE/ace/CDR_Stream.cpp#L503

The `wr_ptr` gets advanced to some alignment, but the bytes between the old and new `wr_ptr` are random.

For example, this snippet of code:
```
std::string s = "event";
ACE_CDR::ULong i = "50";
ACE_OutputCDR ocdr;

ocdr.write_ulong(s.lenght());
ocdr.write_char_array(s.data(), s.length());
ocdr.write_ulong(i);
```
generates the following bytes:
```
00000000  05 00 00 00 65 76 65 6e  74 XX XX XX 32 00 00 00  |....event...2...|
00000010
```

The three bytes `XX XX XX` are the ones that get inserted to align the `i` to a 4-byte boundary and, unfortunately, are not set to 0, but are random. So calling the same serialisation function twice results in different binary results.

It is not a problem when reading with ACE_InputCDR, since the `adjust()` function is called there as well, thus skipping the random bytes. But a hash function cannot be used to compare the two, otherwise identical, objects.

### Sample fix/ workaround

If no solution is found within the ACE framework, we will need to make major changes to our application to serialise objects once and carry that information around.

A suggestion would be to make sure to set all the padding bytes explicitly to 0.

**Comment by mitza-oci** [comment]
It's following the CDR requirements which are apparently different than yours.
There are a number of OutputCDR constructors that give you the option to either provide an existing buffer that you can memset or an allocator that you can provide.
You can also build a different serializer on top of Message Blocks, feel free to start with the one we have here: https://github.com/objectcomputing/OpenDDS/blob/master/dds/DCPS/Serializer.h which provides flexible padding behavior (don't pad, pad with arbitrary bytes, pad with zeros).

**Comment by jwillemsen** [comment]
Have you tried to add ACE_INITIALIZE_MEMORY_BEFORE_USE to your ace/config.h file and rebuild ACE? When that define is set we do initialize some blocks explicitly with zeros

**Comment by JanKalin** [comment]
Thanks for inputs. Looking through the code it seems that ACE_INITIALIZE_MEMORY_BEFORE_USE  will do the trick. We'll check and report back.

**Comment by JanKalin** [comment]
Looking through the code it seems that ACE_INITIALIZE_MEMORY_BEFORE_USE will do the trick. 

And indeed I can report that it does work. Thanks for help!

**Comment by mitza-oci** [comment]
ACE_INITIALIZE_MEMORY_BEFORE_USE will affect every use of Message Blocks including those that are just used within the process and never serialized for storage/network.  This may have a negative performance impact.

**Comment by JanKalin** [comment]
Thanks for the warning. 

We are aware of this, but the application is designed so that the serialisation only occurs on the boundary between the main application and the controlling application and when writing to disk. The first of which is rate-controlled (data gets thrown away if there is any danger of clogging up the main processing pipeline) and the second needs this flag. 

Within the application only pointers to objects are serialised and entered into queues,  a few bytes worth of data, so that the slow-down will be negligible.
