### ISSUE TITLE
Is this documenting comment correct?

### ISSUE THREAD

**Issue by ngrodzitski** [DOCGroup/ACE_TAO#937]
I think the comment is incorrect:

https://github.com/DOCGroup/ACE_TAO/blob/25f5307a46b10ebe7f26f46c006892f0e249c365/ACE/ace/OS_NS_sys_sendfile.h#L35-L40

Found in the doc:
http://www.dre.vanderbilt.edu/Doxygen/6.5.6/html/libace-doc/a03727.html#a5aa5d35fb3a0417767005e02a46fc945

**Comment by jwillemsen** [comment]
No, not, it wraps sendfile, see http://man7.org/linux/man-pages/man2/sendfile.2.html. Please open a PR for a documentation fix

**Comment by ngrodzitski** [comment]
Having
1.
> sendfile - transfer data between file descriptors
2.
> Finds the length of a string (char version). 

How does the second can be translated to the first one?

**Comment by jwillemsen** [comment]
Not, the current documentation is not correct

**Comment by jwillemsen** [comment]
Fixed
