### ISSUE TITLE
Use git branches instead of tags for Latest_*

### ISSUE THREAD

**Issue by mitza-oci** [DOCGroup/ACE_TAO#940]
https://github.com/DOCGroup/ACE_TAO/blob/9d0c34b22345878e61a5765bbd7a48c6791ffe09/ACE/bin/make_release.py#L524

We found a case where Jenkins's git polling didn't detect a change in Latest_*.  Since tags aren't expected to "move," we propose making these branches instead.

**Comment by jwillemsen** [comment]
Feel free to update the script to use branches instead of tags, please make the same changes to CIAO and DAnCE (they use a slightly modified version of the same script).

**Comment by mitza-oci** [comment]
This is causing problems on some of our Jenkins builds.
```
   4d7f65535e..1282610faa  master        -> origin/master
 * [new tag]               ACE+TAO-6_5_8 -> ACE+TAO-6_5_8
 ! [rejected]              Latest_Beta   -> Latest_Beta  (would clobber existing tag)
 ! [rejected]              Latest_Micro  -> Latest_Micro  (would clobber existing tag)
```

**Comment by jwillemsen** [comment]
Same issue now happens according to @mitza-oci for the Latest_ACETAO_Micro tag on MPC

**Comment by iguessthislldo** [comment]
Okay I have the release script setup and working (Or at least [it looks like I did](https://github.com/iguessthislldo-test-org/ACE_TAO/releases)). I got it working with Python 3 along the way.

I have a few questions:
- I'm a little confused why someone why would want to use "Latest_Major" or "Latest_Micro"? Why not just "latest"?
- What am I doing exactly? Am I just making the tags into branches? Or am I keeping the tags and just adding branches.
> please make the same changes to CIAO and DAnCE (they use a slightly modified version of the same script).

- Do each of them have a separate copy, or share one?

**Comment by jwillemsen** [comment]
Latest_Major would be 6.0.0, Latest Minor 6.5.0 and Latest Micro 6.5.10. Personally I always use the latest micro but I know of users who prefer a minor or even major version. That is mostly also history but let us just keep it.

CIAO/DAnCE have their own script.

**Comment by jwillemsen** [comment]
As far as I understood it the proposal from @mitza-oci is to replace the branches with tags because tags are assumed to move where branches are not.

**Comment by iguessthislldo** [comment]
> Personally I always use the latest micro but I know of users who prefer a minor or even major version. That is mostly also history, in the past we had days with multiple beta (micro) releases a day because of basic compile problems due to lack of CI.

If user's want them, then I guess that's enough reason to keep them. They still seem weird to me though.

> CIAO/DAnCE have their own script.

Found them. I will do ACE/TAO first and once that's merged I'll duplicate the changes in the other repos.

> As far as I understood it the proposal from @mitza-oci is to replace the branches with tags because tags are assumed to move where branches are not.

Okay, then I will replace the tags with branches of the same name. I just wasn't sure if there was going to be any problems with setups that might expect them to be tags, so maybe we wanted to keep them and migrate the setups that did have problems to use the branches.

Do you want me to actually change the tags to branches into repos in addition to the script changes, or is this something to do when another release comes around?

**Comment by jwillemsen** [comment]
Sorry, my previous comment was incorrect, your comment was correct, it is replace tags with branches

**Comment by jwillemsen** [comment]
Very likely it is the safest to replace the existing tags with branches right now, than we directly experience when there are any problems with it

**Comment by iguessthislldo** [comment]
I tested the branch changes to the script by doing a mock ACE-TAO 7 release, but hit a problem with `Latest_Major`. If I turn the tag into a branch as is, I can't fast forward it to `master`, like I was going to for all the branches on a release.

```
%git fetch . master:Latest_Major
From .
 ! [rejected]                master     -> Latest_Major  (non-fast-forward)
```

It seems the commit at `Latest_Major` is not an ancestor of `master`, which is not at all what I was expecting:

```sh
%git merge-base --is-ancestor Latest_Minor master && echo "true" || echo "false" 
true
%git merge-base --is-ancestor Latest_Major master && echo "true" || echo "false"
false
```

I'm not sure what the solution is to this except maybe finding another commit to start `Latest_Major` at that is a ancestor of `master`. I'm not sure how to find that commit or if that's right way to solve this though. I guess I could also force the branch to go to `master`, but I was hoping not to do that, especially since I think this is just a problem with the 6.0.0 commit.

**Comment by iguessthislldo** [comment]
If I take out the code for updating `Latest_Major`, the other branches get fast-forwarded just fine. I went ahead and created #1182 for now.

**Comment by jwillemsen** [comment]
Maybe the Latest_Major comes through the conversion of the repositories, more older branches seems to have that problem. Can you find the 6.0.0 release as ancestor of master?

**Comment by mitza-oci** [comment]
43bf8ec8720073eae2997ddbab972a94fbf1e0a9 appears to be the correct commit for 6.0.0

**Comment by iguessthislldo** [comment]
> 43bf8ec appears to be the correct commit for 6.0.0

Okay, Ill use that as the starting point of `Latest_Major` when I create the branches.

**Comment by iguessthislldo** [comment]
MPC appears to have the same problem. I'm going to use https://github.com/DOCGroup/MPC/commit/d9d2f27dde82620c4799d492597f3d0abfb76cf2.
